### ISSUE TITLE
Version number is not bumped

### ISSUE THREAD

**Issue by llaville** [phpro/grumphp#102]
Always fixed to 0.7.0
See  https://github.com/phpro/grumphp/blob/master/src/GrumPHP/Console/Application.php#L21

**Comment by veewee** [comment]
+1
We really need a release script for this :)

**Comment by veewee** [comment]
I added a tag script so that I won't forget to change the version!

**Comment by ravinderk** [comment]
@veewee This will work from next version, means after version 0.7.2 updates, right?

**Comment by veewee** [comment]
@ravinderk 
This is fixed in 0.8.0 and won't happen again.
https://github.com/phpro/grumphp/releases/tag/v0.8.0

**Comment by ravinderk** [comment]
@veewee thank you
<img width="382" alt="screen shot 2016-02-29 at 9 39 19 pm" src="https://cloud.githubusercontent.com/assets/1784821/13400262/f9709f9e-df2c-11e5-85a8-f2d32d39213d.png">
