### ISSUE TITLE
deprecated issue in magento 2.4.4

### ISSUE THREAD

**Issue by palakaccorin** [phpro/grumphp#1028]
I have issue in installing grumphp in latest magento version 2.4.4 
Running below command , throwing errors 
composer require --dev phpro/grumphp
![image](https://user-images.githubusercontent.com/38860012/181757547-07615c25-0710-4da8-8e05-49478e10bfa8.png)

Then, Tried with * in command 
composer require --dev phpro/grumphp:*
It is installing v1.5.1, but throwing deprecated errors at last 
![image](https://user-images.githubusercontent.com/38860012/181757871-f21a9ab1-d17e-4c1a-b095-7dcbf6b1df0e.png)

so how can I install compatible grumphp in magento 2.4.4

**Comment by veewee** [comment]
Hello,

You can either upgrade symfony/console or use the dependencyless phpro/grumphp-shim package or use an older version of grumphp and mute the PHP deprecation warnings.

**Comment by palakaccorin** [comment]
@veewee thanks, it helps. 
phpro/grumphp-shim package works.
