### ISSUE TITLE
Fix Phpcsfixer name

### ISSUE THREAD

**Issue by keradus** [phpro/grumphp#106]
Please, could you fix the name of tool showed on precommit hook?
Proper one is `PHP CS Fixer`, or at least `PhpCsFixer` if you don't like spaces.

**Comment by keradus** [comment]
ping

**Comment by aderuwe** [comment]
@keradus Feel free to contribute a fix. More info here https://github.com/phpro/grumphp/blob/master/CONTRIBUTING.md.

**Comment by veewee** [comment]
This one is fixed in https://github.com/phpro/grumphp/commit/bc97896157eec56c4ae219942150c76d76331964

**Comment by keradus** [comment]
thanks @veewee
