### ISSUE TITLE
Fixed Windows compatibility

### ISSUE THREAD

**Issue by llaville** [phpro/grumphp#107]
While I run tests on my future new task proposal for `php_blacklist` commented in issue #53, I found an error in RegisteredFiles Locator.

See https://github.com/phpro/grumphp/blob/master/src/GrumPHP/Locator/RegisteredFiles.php#L35

`PHP_EOL` must be replaced by `"\n"`

**Comment by llaville** [comment]
See logger helper proposed by PR https://github.com/phpro/grumphp/pull/111

**Comment by veewee** [comment]
Fixed in #112.
I also added Windows CI to make sure we detect this kind of issues earlier.
