### ISSUE TITLE
Provide a security policy for this library

### ISSUE THREAD

**Issue by TravisCarden** [phpro/grumphp#1072]
Hi! I'm currently using GrumPHP on a library created specifically for inclusion in Drupal core (https://github.com/php-tuf/composer-stager), where we have [a policy of evaluating the security policies of packages](https://www.drupal.org/about/core/policies/core-dependency-policies/dependency-info#criteria) before adding them as dependencies. I don't see any such policy here (e.g., at https://github.com/phpro/grumphp/security). Do you have one? If so, would you be kind enough to publish it? If not, would you consider creating one? Thank you!

**Comment by veewee** [comment]
Hello Travis,

Thanks for reporting.
I'll have to look into setting up that specific policy for GrumPHP. 

Do you have any example policies to share?
Because, I couldn't find a security policy for composer-stager either.

**Comment by TravisCarden** [comment]
Sure, @veewee. We're working on defining our security policy right now. Symfony has one at https://github.com/symfony/symfony/security/policy which we're looking at as an example.

**Comment by veewee** [comment]
@TravisCarden I've added a small policy:
https://github.com/phpro/grumphp/blob/master/SECURITY.md

I'm lucky not to have too much experience with security vulnerabilities. (knocks on wood)
So if you find something is missing - feel free to propose alternatives.
