### ISSUE TITLE
GrumPHP in git submodules

### ISSUE THREAD

**Issue by nr404** [phpro/grumphp#109]
I tried to add GrumPHP to a repo that is a submodule of another repository but is doesn't quite work.

If I use the default git directory in the config the git:init breaks because it tries to access the wrong directory.
As the submodule directory ( /home/user/Code/repo-with-submodules/submodule-name/ ) does not have its own .git directory and the hook should be created in /home/user/Code/repo-with-submodules/.git/modules/submodule-name/

using ../ obviously sets them for the wrong repo

Currently I don't really have an idea how to fix this without running something like 'git rev-parse --git-dir' to get the actual hook directory and maybe also introduce a overwriteable working directory.

**Comment by veewee** [comment]
Hi @nr404,

Currently gitlib, the git library we are using, does not support git submodules. 
More info van be found at: https://github.com/phpro/grumphp/blob/master/doc/issues/grumphp-is-not-working-with-submodules.md

As long as this is not supported, it will be hacking around this issue.
