### ISSUE TITLE
The application requires the version "^7.2" or greater.

### ISSUE THREAD

**Issue by floriankraemer** [phpro/grumphp#1128]
| Q               | A
| --------------- | ---
| Version         | ?
| Bug?            | yes
| New feature?    | no
| Question?       | no
| Documentation?  | no
| Related tickets | -

I've installed grumphp via Phive and I think something is off with the version of something. The error message could be way more clear. `The application requires the version "^7.2" or greater.` - The version of WHAT exactly? PHP? grump?

```sh
PHP 8.3.4 (cli) (built: Mar 16 2024 08:39:49) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.3.4, Copyright (c) Zend Technologies
    with Xdebug v3.3.1, Copyright (c) 2002-2023, by Derick Rethans
    with Zend OPcache v8.3.4, Copyright (c), by Zend Technologies
```

**Steps to reproduce:**
```sh
phive install grumphp
tools/grumphp --version
```

**Result:**
```
Box Requirements Checker
========================

> Using PHP 8.3.4
> PHP is using the following php.ini file:
  /etc/php/8.3/cli/php.ini

> Checking Box requirements:
  E...


 [ERROR] Your system is not ready to run the application.


Fix the following mandatory requirements:
=========================================

 * The application requires the version "^7.2" or greater.
```

**Comment by veewee** [comment]
Hello,

What version of grumphp are you installing through phive?
It seems to be a rather old one?

I just tried and it works as expected on PHP 8.3

![Screenshot 2024-03-23 at 18 54 11](https://github.com/phpro/grumphp/assets/1618158/6e399afe-5f52-4a6c-b9a6-76794700c2f4)
![Screenshot 2024-03-23 at 18 54 20](https://github.com/phpro/grumphp/assets/1618158/6832e3e9-e9de-4b55-9583-91ff43b5e0f5)

**Comment by floriankraemer** [comment]
Oh, you are right. `<phar name="grumphp" version="^0.19.1" installed="0.19.1" location="./tools/grumphp" copy="false"/>` but why did it install such an old version? My assumption was that `phive install phpgrump` would install the latest version.

Sorry for the inconvenience!
