### ISSUE TITLE
Support for multiple PHPStan tasks

### ISSUE THREAD

**Issue by szymach** [phpro/grumphp#1130]
| Q               | A
| --------------- | ---
| Version         | any
| Bug?            | no
| New feature?    | no
| Question?       | yes
| Documentation?  | no
| Related tickets | comma-separated list of related tickets

From what I understand, you can only describe a single PHPStan task. In my company, we have introduced PHPStan to a legacy project, where we defined multiple configuration files. We have a bash script that runs all of them, however we would prefer to configure these as actual PHPStan tasks. Is this possible? Would you consider it? Thank you :)

**Comment by veewee** [comment]
That's already possible:
https://github.com/phpro/grumphp/blob/v2.x/doc/tasks.md#run-the-same-task-twice-with-different-configuration

**Comment by szymach** [comment]
Ah, thank you, I did miss that :)
