### ISSUE TITLE
Add coverage option to infection task

### ISSUE THREAD

**Issue by jose-bittacora** [phpro/grumphp#1159]
| Q               | A
| --------------- | ---
| Version         | GrumPHP 2.9.0
| Bug?            | no
| New feature?    | yes
| Question?       | no
| Documentation?  | no
| Related tickets | none

First of all thank you for GrumPHP, it is a tool that is not missing in any of my projects.

I think it would be a good idea to add a configuration option to the Infection task, to be able to specify the `--coverage` option, as indicated here: [--coverage option](https://infection.github.io/guide/command-line-options.html#coverage). This way, if the coverage is already generated in another task (e.g. `paratest` or `phpunit`), the infection task will run much faster.

If present, the [--skip-initial-tests](https://infection.github.io/guide/command-line-options.html#skip-initial-tests) should be added to the command when executed too.

Thank you very much

**Comment by veewee** [comment]
Thanks for your kind words.

It makes a lot of sense to introduce them.
Would you care to craft a PR in order to make this happen?

**Comment by jose-ba** [comment]
> Thanks for your kind words.
> 
> It makes a lot of sense to introduce them. Would you care to craft a PR in order to make this happen?

Here it is: https://github.com/phpro/grumphp/pull/1160

**Comment by veewee** [comment]
We'll continue in the PR. Thanks.
