### ISSUE TITLE
CI failures 

### ISSUE THREAD

**Issue by llaville** [phpro/grumphp#118]
I've noticed (with https://github.com/phpro/grumphp/pull/108) that Travis jobs and AppVeyor  jobs failed due to conflict between Composer and SecurityAdvisories. 

See https://github.com/phpro/grumphp/blob/master/composer.json#L24 and https://github.com/Roave/SecurityAdvisories/blob/master/composer.json#L17.

This is the reason why I recommand to change Composer version from `"^1.0-alpha11"` to `"@dev"`

**Comment by veewee** [comment]
Hello @llaville,

I am wondering if this project needs the security advisories.
This is something you might want to add to your own application to make sure that no insecure library is being used.
For this package, a broad range of library versions are supported. So the security advisories don't make much sense in this context.
We still suggest the package to the applications that are using GrumPHP. What do you think?

**Comment by llaville** [comment]
Hello Toon,

I agree with you, in CI context, adding the security advisories don't make sense. It's probably better to remove it from grumphp.yml on Travis and AppVeyor platforms rather than modify the composer requirment, as I've previously suggested.

Laurent

**Comment by veewee** [comment]
This one is fixed by: https://github.com/phpro/grumphp/commit/ba1b582f262b47cc0794831f1e8ffc86fb949fad

We've chosen not to include any security checks in the code of grumphp. We are supporting a broad range of packages, so it's the responsibility of the implementing application to enable the security advisories.
