### ISSUE TITLE
Generate report in file

### ISSUE THREAD

**Issue by DnD-Merlin** [phpro/grumphp#121]
Hello,

I am using grumphp especially in a continious integration process, it be great if the run command can take an output report file for the global report.
Something like 
`php ./vendor/bin/grumphp run --report-file=/path/to/report.txt`
And with that nothing will be shown on the command output.

Maybe this is already possible, if that is the can can someone give me a hint on how to do this ?

Thanks !

**Comment by veewee** [comment]
Maybe something like this?

```
php ./vendor/bin/grumphp run  >> /path/to/report.txt 2>&1
```
In our next version, it will be possible to specify your own loggers. This one might require some more work. For more information, take a look at: https://github.com/phpro/grumphp/pull/114

**Comment by DnD-Merlin** [comment]
Yes I think this might be the right solution !
OK great I will take a look at this loggers.

Thank you !
