### ISSUE TITLE
Add Gherkin syntax checker task

### ISSUE THREAD

**Issue by tifabien** [phpro/grumphp#128]
As there is a behat task already created in the project maybe we could add a checker for scenarios wrote with the Gherkin syntax.

I took a look an found this project https://github.com/malukenho/kawaii-gherkin which could do the job.

What do you think?

**Comment by veewee** [comment]
@tifabien,
A gherkin linter sure looks like a great addition! 
We would like to avoid automatic file changes, but the check can be used for the task.

**Comment by tifabien** [comment]
That's what I was thinking of. With the check command we could do the same thing as the phpcsfixer task :)

**Comment by veewee** [comment]
Hello @tifabien,

Can you take a look and test the PR I created for this issue?
https://github.com/phpro/grumphp/pull/131

Currently I don't have any projects with feature files anymore. Feel free to make or suggest improvements to the task.

**Comment by tifabien** [comment]
Hi @veewee 

For sure! I'll have a look at it tomorrow and let you know if all runs well !

**Comment by tifabien** [comment]
I started playing with my gherkin features and seems that kawaii is lost with them. 
I don't know if it is related to the fact that i'm running command in Windows.

Also I tried to install kawai in my symfony3 project and it failed as 3.0 version of symfony components is not added in the composer.json.

Maybe to early to add this task in the master branch...

**Comment by tifabien** [comment]
I created issue on kawai project. let's see if the issue is only my side

**Comment by veewee** [comment]
Maybe it's indeed a bit to early. Support for Symfony 3 is no must, but I would really appreciate it.
Please keep me posted on the kawaii issue.

Thanks!

**Comment by veewee** [comment]
@tifabien 
Even though the tool isn't stable yet, I added the task to master. 
Early adapting for the win!

**Comment by tifabien** [comment]
@veewee No problem for me as the project now support SF3 components and fixed issue on Widows platform so that's a good news!!
