### ISSUE TITLE
Standard is not a required argument for PHPCS

### ISSUE THREAD

**Issue by Anahkiasen** [phpro/grumphp#129]
The PHPCS task's configuration forces you to specify a `standard` option, in my case I have a `ruleset.xml` that PHPCS recognizes naturally but since Grumphp passes a default of PSR2 I have no way to override it and let PHPCS use the standard specified in the XML file. Is there a way to unset an option?

**Comment by Anahkiasen** [comment]
Currently doing this but it's a bit counter-intuitive:

```yaml
phpcs:
    standard: "phpcs.xml"
```

**Comment by veewee** [comment]
I haven't been using custom rulesets but as far as I can read in the documentation, the way of specifying rulesets is by setting the `standard` option:
https://pear.php.net/manual/en/package.php.php-codesniffer.annotated-ruleset.php

This may seem counter-intuitive, but we tend to follow the CLI usage of the tools we are running.
Can you verify if this is the way to set the custom ruleset file?

**Comment by Anahkiasen** [comment]
It is, what I meant is it requires extra configuration whereas when I run the tool I just do `$ phpcs`. But this issue was more on the subject of whether it would be beneficial to add a way to remove default arguments set on the tools, like `standard: null` or something like that?

**Comment by veewee** [comment]
I dove a bit deaper in the documentation of phpcs:

> Source: https://pear.php.net/manual/en/package.php.php-codesniffer.usage.php
> The --standard command line argument is optional, even if you have more than one coding standard installed. If no coding standard is specified, PHP_CodeSniffer will default to checking against the PEAR coding standard, or the standard you have set as the default. The default can be set by setting the `default_standard` option.

I can't find documentation about a custom standard being used without specifying the standard option.

So as far as I can tell, the standard that is being used depends on the user configuration. In GrumPHP we would like it to run on the project specified configuration. So we would rather have a hardcoded standard by default which you can explicitily overwrite in the configuration file.
Currently that is  the PSR-2 php-fig standard.

**Comment by veewee** [comment]
@Anahkiasen Is this still an issue for you or is the answer above clear?

**Comment by Anahkiasen** [comment]
Had missed your message. PHPCS does defaultl to the PEAR standard if no standard is passed but it also defaults to reading the `phpcs.xml` file if present, in which you can specify which standard to use, is what I meant. Thus forcing the user to pass a standard might be counterintuitive as if in your phpcs.xml you specify standard A but Grumphp specifies PSR2 behind your back, you'll get errors you might have disabled, etc

**Comment by veewee** [comment]
Sounds good. I will try to change logic in the upcoming version.

**Comment by veewee** [comment]
The code got merged in #136. Thanks for the remark!
