### ISSUE TITLE
Run grumphp in a docker container

### ISSUE THREAD

**Issue by jverdeyen** [phpro/grumphp#152]
| Q | A |
| --- | --- |
| Branch | master |
| Bug? | no |
| New feature? | no |
| Question? | yes |
| Documentation? | no |

In short:
I'm developing php applications in docker containers. It's a lightweight vagrant box with a docker server.
The OS X docker client connects with it as it was native.

This means:
- Everything related with git is on OS X cli.
- Everything related with composer and bin executables are on the PHP container.

I would like to extend grumphp in the way that the pre-commit hook command executes in the docker container.

Example to run grumphp using docker and docker-compose from OS X cli:

``` bash
docker exec -it `docker-compose ps -q php` bash -c "cd /var/www/app && ./vendor/bin/grumphp run";
```

I can make something like the vagrant pre-commit settings:
https://github.com/phpro/grumphp/blob/master/resources/hooks/vagrant/pre-commit

But I'll need some extra parameters, which container (`php`) and which docroot (`/var/www/app`).
The git diff can be done on the OS X cli but the run should happen on the container.

Can I add a `docker` parameter, with all settings?
Hooks can be installed local as default.

I'm currently using it by hardcoding this in the `pre-commit` hook.

```
# Run GrumPHP
#(cd "./" && echo "${DIFF}" | exec '/vendor/phpro/grumphp/bin/grumphp' 'git:pre-commit' '--skip-success-output')
(cd "./" && echo "${DIFF}" | docker exec -i `docker-compose ps -q php` bash -c "cd /var/www/app && ./vendor/bin/grumphp git:pre-commit --ansi --skip-success-output")
```

A gist:
https://gist.github.com/jverdeyen/9c0b247bb8b34c7fae514315db36a23e

I would like to hear feedback about this :)

Thanks!

**Comment by veewee** [comment]
Hello @jverdeyen,

A docker preset sure sounds look a nice addition!
In your gist: how does the docker container get access to the commit message file? I don't think this will work but haven't tried it.

With the vagrant preset files, we tried to avoid setting additional parameters in the yaml file. We did this to make sure that the configuration was preset independent. The disadvantage of this approuch is that a home directory needs to be set in the vagrant box.

Maybe it's a better idea to provide something like a `git_hooks_variables` parameter which can be used to fill replacements. For example:

```yaml
parameters:
    git_hook_variables:
         DOCKER_CONTAINER: php
         DOCKER_HOME_DIRECTORY: /app/something
```

With this approach the git:init command can replace the variables in the git hooks. Maybe it's best to make the replacements bash variables: ${DOCKER_CONTAINER} to make sure that code inspection doens't flip.

Feel free to implement. It sure looks like a great next step!

**Comment by jverdeyen** [comment]
Hi @veewee !

The container also has `git` installed, but the cli doesn't support auto-complete etc.. The git commands also take ages since the repo is synced over nfs (filesystem os x -> vagrant (nfs) -> docker container).
I currently haven't used the message checker to verify it really works.

The `git_hooks_variables` seems like a good idea!

The main concern is the re-usability of this feature, we are using a very specific way of developing in docker with docker-compose (http://tech.yappa.be/docker-php-development).

I'm reviewing this with our dev team. For now we create commit hooks in our home folder and symlink them into projects.

Thanks for your input! I'll do some testing :)

👍 big up for grumPHP!

**Comment by schrapel** [comment]
docker exec doesn't make much sense here. We should create a docker container by building upon the official php cli image and do a docker run command against the build.

**Comment by veewee** [comment]
@schrapel 
It depends what tasks you want to run. For regular tasks like phpunit and phpcs a custom container is possible. If you want to run e.g. selenium stuff, you may want to run the tests in the environment you are working in. 

As mentioned above, I think it's best to make the container configurable like this:

```
parameters:
    git_hook_variables:
         DOCKER_CONTAINER: php
```

Extra info:
I did manage to run the `grumphp run` command in a docker container during CI on pipelines and described it here:
http://veewee.github.io/blog/grumphp-approves-bitbucket-pipelines/

**Comment by schrapel** [comment]
Personally I think tests should be run in a separate container for testing so it cannot be affected by your dev environment. Obviously the two environments would need to be the same but the test would likely have more dependencies

I actually found that blog post yesterday, so thanks for that

**Comment by veewee** [comment]
As mentioned in #232: We won't maintain a Dockerfile ourselves. 
However, we would accept configurable git hooks for Docker as mentioned above.

**Comment by bircher** [comment]
as a workaround I added a shim to my system...

`php` on my host system is now: 
```bash
#!/bin/sh
docker exec -it $(docker-compose ps -q php) php "$@"
```

But I would not be against grumphp being configurable to run in my container.

**Comment by ceesvanegmond** [comment]
@veewee Maybe it's better to implement an 'custom' hook. Here you can just specify a specific command you want to execute. Allot of people are using docker, or maybe docker_compose (as we do). I head even some people even use bash scripts for this.

I suggest creating a new `custom` hook_preset, and expand the ```parameters.yml``` with something like this:

```yaml

    git_hook:
        custom:
            shell: 'docker-compose -f docker-compose.dev.yml'
```

or
```yaml

    git_hook:
        custom:
            shell: '/bin/bash scripts.sh'
```

We can basically copy the existing `pre-commit` and `commit-msg` files and update the command with the one you set in the above YAML file.

What do you think?

**Comment by veewee** [comment]
@ceesvanegmond, Thanks for the suggestion. I am not sure what the resulting hook file looks like. Can you add an example?
Currently it is possible to use your custom hook templates, so that is also an option.

**Comment by peterjaap** [comment]
Ping @JeroenBoersma

**Comment by JeroenBoersma** [comment]
I've installed git inside my docker containers, so if I use `git commit` I make sure this happens from inside the project php container, this way the GrumPHP will also run in the correct environment.

At first, I had some trouble with passing variables for author(first- lastname) to the php container, what basically happens is that first- and lastname become 2 parameters for the GrumPHP command.
By running `git commit` inside the docker container this is all resolved.

**Comment by lephleg** [comment]
Any progress on this? I'd really like to avoid installing GrumPHP dependencies on my host...

**Comment by nntoan** [comment]
@veewee Why this is closed?

**Comment by veewee** [comment]
Since you already can run GrumPHP inside docker.
More info: https://github.com/phpro/grumphp/blob/master/doc/parameters.md
```
parameters:
    git_hook_variables:
        EXEC_GRUMPHP_COMMAND: 'docker ....'
```

**Comment by indapublic** [comment]
Hi, @veewee!

Seems like EXEC_GRUMPHP_COMMAND is ignored for my configuration. I have PHP installed locally (i'm using OSX) and looks like my local php interpretator is used 

**grumphp.yml**
```
parameters:
    git_hook_variables:
        EXEC_GRUMPHP_COMMAND: docker-compose COMPOSE_ARGS=-f ./docker/docker-compose.yml run php php
    tasks:
        phpcsfixer2:
            config: .php_cs
            using_cache: ~
            verbose: true
```

I can print anything in EXEC_GRUMPHP_COMMAND (`foobar` for example) and I will receive grumphp standard output

```
phpro/grumphp                         v0.16.1            A composer plugin that enables source code quality checks.
```

Could you give some advices how to fix it? Thanks.

**Comment by veewee** [comment]
Hi @indapublic,

You can debug the generated .git/hooks files to see what that results in.
Feel free to open up a new support issue since this one is closed.

**Comment by indapublic** [comment]
Thanks, @veewee. I see `exec` in `pre-commit`.

```
(cd "./" && printf "%s\n" "${DIFF}" | 'exec' 'vendor/phpro/grumphp/bin/grumphp' 'git:pre-commit' '--skip-success-output')
```

**grumphp.yaml**
```
parameters:
    git_hook_variables:
        EXEC_GRUMPHP_COMMAND: asdasdsa
    tasks:
        phpcsfixer2:
            config: .php_cs
            using_cache: ~
            verbose: true
```

Should I regenerate (flush cache, for example) git hook files?

**Comment by veewee** [comment]
When changing those settings, you need to run `grumphp git:init`

**Comment by indapublic** [comment]
@veewee Awesome. Thanks! Missed it in documentation [here](https://github.com/phpro/grumphp/blob/master/doc/parameters.md)

**Comment by strikernl** [comment]
This example from the [documentation](https://github.com/phpro/grumphp/blob/master/doc/parameters.md) does not work for me in grumphp 1.8.0, it does not seem to resolve the variable `$(pwd)`:

```yaml
EXEC_GRUMPHP_COMMAND: 'docker run --rm -it -v $(pwd):/grumphp -w /grumphp webdevops/php:alpine'
```

I then run `git commit`.

First it complains about this: `the input device is not a TTY`, which is fixed by change `-it` into `-i`.

Then it returns
```
docker: Error response from daemon: create $(pwd): "$(pwd)" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path.
See 'docker run --help'.
```

Perhaps because it's put in single quotes in the resulting `pre-commit`?

```
'docker' 'run' '--rm' '-it' '-v' '$(pwd):/grumphp' '-w' '/grumphp' 'webdevops/php:alpine' 'vendor/phpro/grumphp/bin/grumphp' 'git:pre-commit' '--skip-success-output'
```
