### ISSUE TITLE
Add php linter task

### ISSUE THREAD

**Issue by sc0rp10** [phpro/grumphp#165]
| Q               | A
| --------------- | ---
| Branch          | master for features and deprecations
| Bug?            | no
| New feature?    | yes
| Question?       | no
| Documentation?  | no
| Related tickets | 

It's be very useful if you add https://github.com/JakubOnderka/PHP-Parallel-Lint task for fast parallel files linting

**Comment by veewee** [comment]
It looks like a great addition. Can it also take changed files as input parameter?
Feel free to implement.

**Comment by sc0rp10** [comment]
```
sc0rp10 @ work:/tmp $ ./vendor/bin/parallel-lint foo.php bar.php
PHP 7.0.9 | 10 parallel jobs
.                                                            2/2 (100 %)


Checked 2 files in 0 seconds
No syntax error found
```

Yes, It is.

**Comment by veewee** [comment]
Added in PR #182 .
