### ISSUE TITLE
How can I run shell command?

### ISSUE THREAD

**Issue by sc0rp10** [phpro/grumphp#169]
| Q | A |
| --- | --- |
| Branch | master |
| Bug? | yes |
| Question? | yes |

I need to run some console command on pre-commit stage. e.g. `./bin/console translation:check-catalogue --env=dev -vvv`
Now I unable to do it: I got `/bin/sh: ./bin/console translation:check-catalogue --env=dev: No such file or directory` error.
I can create shell file with single line for this, but it is not comfortable.
How can I do it?

**Comment by veewee** [comment]
Currently that is not possible.
The process builder is translating this to:

```sh
'sh' './bin/console translation:check-catalogue --env=dev'
```

As you can see, there are single quotes around all the input. This means that it is handled as one argument.
The code of the Shell task could be improved to make sure that multiple arguments.

**Comment by bvanderstee** [comment]
I'll be working on this issue
