### ISSUE TITLE
Bug in Blacklist task

### ISSUE THREAD

**Issue by sc0rp10** [phpro/grumphp#171]
| Q               | A
| --------------- | ---
| Branch          | master
| Bug?            | yes
| New feature?    | no
| Question?       | no
| Documentation?  | no

**My configuration**
I've created demo repository with minimal config for this bug: https://github.com/sc0rp10/grumphp-blacklist-bug

**Steps to reproduce:**
```sh
# Clone repository
composer install
# open file src/index.php in editor
# change 'private' keyword to 'protected'
# commit changes (success) or run GrumpHP
# open src/index.php again
# change back 'protected' to 'private'
# commit changes (success) or run GrumpHP
```

**Result:**
Expected result in second case is error: keyword 'private' is blacklisted, but if repeat these steps, GrumpHP missed keyword every second run.

**Comment by veewee** [comment]
Hi @sc0rp10,

Thanks for reporting the bug.

I've checked out your repo and tested the case as specified above.
It seems to work just fine here. Maybe I am not understanding the flow, but I've tried:

```sh
git add -A
git commit -m"Test"
# And
git commit -am"Test"
```

After changing the files. Always the same result: with protected properties I see a pass which is normal, with private properties I get a fail.

Maybe you can validate the command that is running?
Here it looks like this:

```
'git' 'grep' '--cached' '-n' '-e' 'die(' '-e' 'var_dump(' '-e' 'exit;' '-e' 'private \$' '-e' 'private static \$' '-e' 'private function' '-e' 'private static function' 'src/index.php'
```

Also know that we are planning to include a php parser to make it easier to blacklist PHP specific stuff in the future (see #138)

**Comment by sc0rp10** [comment]
Hi, @veewee!
If it can help to you, I've recorded short screencast with this bug: https://cdn.weblab.pro/kc21n.mp4

**Comment by sc0rp10** [comment]
And I simplified grumphp.yml only for one keyword, please pull, if you interested

**Comment by veewee** [comment]
Owkay, I see now ...
It is related to #144:

If you use `git commit -a`, the files are only staged in the current running process.
For validating the blacklist, the `git grep --cached` command runs in a separate process
This means that `git grep --cached` will not see the changes.

In current implementation, there isn't really anything we can do about this.
Your issue should not occur, if you commit with the commands:

```
git add .
git commit -m"Not ok!"
````

**Comment by sc0rp10** [comment]
oww, how strange! but thanks for help, you're really helped me!

**Comment by veewee** [comment]
No problem! :)
