### ISSUE TITLE
Add GrumPHP to The PHP Quality Assurance Toolchain

### ISSUE THREAD

**Issue by MetalArend** [phpro/grumphp#183]
On http://phpqatools.org/ you can find a few PHP QA tools, might be interesting to add a pull request to https://github.com/sebastianbergmann/phpqatools.org

**Comment by veewee** [comment]
@MetalArend, Thanks for pointing me to that repository.
I've added a PR. Let's hope it gets merged :)

https://github.com/sebastianbergmann/phpqatools.org/pull/7
