### ISSUE TITLE
Switch to Semver 2.0.0

### ISSUE THREAD

**Issue by Kanti** [phpro/grumphp#188]
| Q               | A
| --------------- | ---
| Branch          | master
| Bug?            | no
| New feature?    | no
| Question?       | yes
| Documentation?  | no
| Related tickets | https://github.com/mrdoob/three.js/issues/3102 https://github.com/tools/godep/issues/420 

Why not semver?
http://semver.org/#why-use-semantic-versioning

## meaning
Given a version number MAJOR.MINOR.PATCH, increment the:

- MAJOR version when you make incompatible API changes,
- MINOR version when you add functionality in a backwards-compatible manner, and
- PATCH version when you make backwards-compatible bug fixes.
Additional labels for pre-release and build metadata are available as extensions to the MAJOR.MINOR.PATCH format.

## example (next versions)
- for a Bugfix: *0.9.5*
- for a Feauter: *0.10.0*
- for a BreakingChange: *1.0.0*

_current version 0.9.4_

## next version should be 1.0.0
according to this:
http://semver.org/#how-do-i-know-when-to-release-100
grumphp should have atleest version 1.0.0

**Comment by veewee** [comment]
We are currently doing SemVer but we are still in 0.X version:

> Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.

There are still some thing I want to implement which will probably break BC. Therefor I would like to keep it as under development for now.
When working on 0.X the semver document is rather loose in my opinion. So currently we are working as followed:

- MAJOR version is still 0.
- MINOR version is upgraded when we are releasing some BC breaks.
- PATCH version is upgraded when new functionality is added or bugs are fixed

As the document states:
> If your software is being used in production, it should probably already be 1.0.0. If you have a stable API on which users have come to depend, you should be 1.0.0. If you’re worrying a lot about backwards compatibility, you should probably already be 1.0.0.

It's a development tool, so it's not being used in production. I currently want to keep on evolving without worrying about BC untill the features which might break BC are developed. From that point on, we will tag 1.0.0 and follow the semver document.

I do hope to get at the 1.0.0 version soon, but I currently struggle to find the time to implement these features.

Your feedback on the matter is more then welcome!

**Comment by Kanti** [comment]
We use GrumPHP within Jenkins for our production systems. But I get your point. I hope that you can take the time to implement these features. And than get version 1.0.0 out there soon.
