### ISSUE TITLE
Add phpdcd task

### ISSUE THREAD

**Issue by veewee** [phpro/grumphp#191]
| Q               | A
| --------------- | ---
| Branch          | master
| Bug?            | no
| New feature?    | yes
| Question?       | no
| Documentation?  | no
| Related tickets | 

More info https://github.com/sebastianbergmann/phpdcd

**Comment by DannyvdSluijs** [comment]
@veewee phpdcd is no longer maintained. Are you sure on adding it ?

**Comment by veewee** [comment]
@DannyvdSluijs: I did not know that is was no longer maintained. Let's close this one since it doesn't look up-to-date anymore. Do you know of a tool that does similar stuff?
