### ISSUE TITLE
Add Humbug task

### ISSUE THREAD

**Issue by veewee** [phpro/grumphp#193]
| Q | A |
| --- | --- |
| Branch | master |
| Bug? | no |
| New feature? | yes |
| Question? | no |
| Documentation? | no |
| Related tickets |  |

More info https://github.com/padraic/humbug

**Comment by pamil** [comment]
Does it make sense to use Humbug? Its results should be interpreted by a human as there are no computable metrics to tell whether they are good or bad.

**Comment by veewee** [comment]
@pamil, I haven't used HumBug myself yet. Somebody suggested a HumBug task long ago.
As far as I can tell, the json log file can be used to get the metrics in the summery part.
Just as in the clover coverage task, it is possible to add a minimum level for one of the metrics `covered_code`, `combined_score` or `mutation_coverage`. 

Example log:

```json
{
    "summary": {
        "total": 416,
        "kills": 24,
        "escapes": 8,
        "errors": 0,
        "timeouts": 0,
        "notests": 384,
        "covered_score": 75,
        "combined_score": 6,
        "mutation_coverage": 8
    },
    "uncovered": []
}
```

I do agree that the results itself should be interpreted by a human to make sure that it aren't false positives. But the calculated metrics could be used to determine how well the tests are being written.

**Comment by exussum12** [comment]
As a note. Humbug is deprecated now. This should be updated to infector

**Comment by veewee** [comment]
Thanks for reporting @exussum12.
Closing this issue since infection is already implemented:
https://github.com/phpro/grumphp/blob/master/doc/tasks/infection.md
