### ISSUE TITLE
NPM scripts task

### ISSUE THREAD

**Issue by veewee** [phpro/grumphp#208]
| Q               | A
| --------------- | ---
| Branch          | master
| Bug?            | no
| New feature?    | yes
| Question?       | no
| Documentation?  | no
| Related tickets | 

Run a specific script from the nodejs package.json file with npm.

https://docs.npmjs.com/misc/scripts

**Comment by Asuza** [comment]
What script is supposed to be run via npm?

**Comment by veewee** [comment]
@Asuza,
It should be configurable like the [grunt](https://github.com/phpro/grumphp/blob/master/doc/tasks/grunt.md) task.

It looks like @Kanti picket it up already :)
