### ISSUE TITLE
Composer scripts task

### ISSUE THREAD

**Issue by veewee** [phpro/grumphp#212]
| Q               | A
| --------------- | ---
| Branch          | master
| Bug?            | no
| New feature?    | yes
| Question?       | no
| Documentation?  | no
| Related tickets | 

Run a specific script from the composer.json file with composer.

https://getcomposer.org/doc/articles/scripts.md#running-scripts-manually

The script to run should be configurable, just like the [grunt](https://github.com/phpro/grumphp/blob/master/doc/tasks/grunt.md) task.

**Comment by Kanti** [comment]
I will pick this one.
