### ISSUE TITLE
Class 'ProxyManager\Configuration' not found (on commit)

### ISSUE THREAD

**Issue by xero88** [phpro/grumphp#219]
Hi,

I can't commit now, I got : 

`Error:PHP Fatal error:  Uncaught Error: Class 'ProxyManager\Configuration' not found in /vendor/symfony/symfony/src/Symfony/Bridge/ProxyManager/LazyProxy/Instantiator/RuntimeInstantiator.php:36`

My grumphp.yml : 

`parameters:
git_dir: .
    bin_dir: vendor/bin
    tasks:
        codeception: ~
        #phpcs: ~
`

Thank you

**Comment by veewee** [comment]
HI @xero88,

Can you copy your composer.json file and the output from the command `composer show` in this ticket?
If you don't see the package `ocramius/proxy-manager` in the list, you will need to require it.
However, it should be required by default.

Thanks

**Comment by xero88** [comment]
Hi, 

Thank you for your answer, the package ocramius/proxy-manager was missing

It's resolved.

Thank you !

Cheers
