### ISSUE TITLE
Add Phan task

### ISSUE THREAD

**Issue by jyggen** [phpro/grumphp#226]
| Q               | A
| --------------- | ---
| Branch          | master
| Bug?            | no
| New feature?    | yes
| Question?       | no
| Documentation?  | no
| Related tickets | n/a

[Phan](https://github.com/etsy/phan) is a static analyzer that looks for common issues and will verify type compatibility on various operations when type information is available or can be deduced. Phan does not make any serious attempt to understand flow control and narrow types based on conditionals.

Will probably send a PR of this myself in the near future, but if anyone else wants to grab it feel free :)

**Comment by tombevers** [comment]
I've started working on this feature

**Comment by veewee** [comment]
Implemented in #336.
