### ISSUE TITLE
Custom Task Examples

### ISSUE THREAD

**Issue by mattgaviota** [phpro/grumphp#235]
| Q               | A
| --------------- | ---
| Branch          | master for features and deprecations
| Bug?            | no
| New feature?    | no
| Question?       | no
| Documentation?  | yes

Hi, I would like to ask for a more exhaustive example for custom tasks. I was trying to make one without too much success. 
I tried to replicate the phpunit task to use paratest instead. But when trying to register it in the service manager it fails with an Uncaught ReflectionException and I do not know where to continue.

Thanks in advance.

**Comment by veewee** [comment]
Hi @mattgaviota,

Is it possible that the task class can't be autoloaded?
You'll have to add the namespace to the autoload section of your composer.json file so that PHP knows where to find your class.

**Comment by mattgaviota** [comment]
Thanks for your fast answer. I already made it work.

**Comment by veewee** [comment]
No problem! :)
