### ISSUE TITLE
How can I just add a few regular expressions to validate?

### ISSUE THREAD

**Issue by Bilge** [phpro/grumphp#257]
| Q               | A
| --------------- | ---
| Question?       | yes

I just want to add a list of regular expressions that must pass for each commit. This should be a simple task but the documentation is not clear on how to do this at all. How do I do this?

**Comment by jyggen** [comment]
It depends on what you want to match the regexps against really. File names? File contents? Commit messages?

**Comment by Bilge** [comment]
File contents.

**Comment by veewee** [comment]
Hello @Bilge,

Currently there is no task for matching file contents against regexes. If you e.g. want to check class docblocks for copyright information, you could use the [`phpparser`](https://github.com/phpro/grumphp/blob/master/doc/tasks/phpparser.md) task, but you would have to create your own visitor.
Another option is to create a task that matches file content against a regular expression.

**Comment by Bilge** [comment]
Do I understand the correct way to implement this is to write a custom task?

**Comment by veewee** [comment]
Yes, you'll need to create your own task for that.
