### ISSUE TITLE
Does GrumPHP support automatic fixing?

### ISSUE THREAD

**Issue by Bilge** [phpro/grumphp#259]
| Q               | A
| --------------- | ---
| Question?       | yes

The animated introduction shows that, "PHPCBF CAN FIX THE 1 MARKED SNIFF VIOLATIONS AUTOMATICALLY". I understand this is a message from phpcs and not GrumPHP directly, but does GrumPHP have support for fixing violations directly or can it only notify about problems?

**Comment by Kanti** [comment]
GrumPHP dose not autofix things for you.
more Information for this decision: #110

**Comment by Bilge** [comment]
@Kanti Thank you. I suggest information gleaned from my recent round of questions be added to the documentation to make key decisions like this clear to all users.

**Comment by veewee** [comment]
the feedback on this issue will be added to the documentation. In the meantime, I created #265 to keep track on this change. I'll close this issue for now.

**Comment by Mte90** [comment]
The copy and paste of the command is very uncomfortable because eveyr parameter and command is wrapped inside `'`  so I have to clean manually. 
Maybe a command like `-fix`  can be helpful if run the phpcbf automatically.

**Comment by Bilge** [comment]
Every parameter is supposed to be quoted. You don't have to "clean" anything. Also your comment has nothing to do with this (closed) issue so kindly refrain from further comment.
