### ISSUE TITLE
Hook still present after removing GrumPHP

### ISSUE THREAD

**Issue by tombevers** [phpro/grumphp#26]
After removing GrumPHP with composer, the hook referring to the GrumPHP is still present. This prevents me from committing unless I remove the hook manually.

This can be annoying for people just trying out GrumPHP and they decide to remove it from their project.

**Comment by veewee** [comment]
Hello @tombevers,

I tested this issue with following set of commands:
```sh
mkdir grumtest
cd grumtest
composer init
composer require --dev phpro/grumphp
composer remove phpro/grumphp
```

The command outputs: `GrumPHP stopped sniffing your commits! Too bad ...`
The git hook is removed.

Next I tried by manually remove the phpro/grumphp entry from composer.json, followed by a `composer update`. The same result.

Can you tell me how to reproduce this issue?
Maybe you don't have write access to the git hook, for example in a vagrant box?
Maybe you deleted the folder from the vendor?

Thanks for reporting!

**Comment by tombevers** [comment]
I tried it again and it works as supposed to ... I can't reproduce it anymore.
