### ISSUE TITLE
Which parts of the code does GrumPHP scan?

### ISSUE THREAD

**Issue by Bilge** [phpro/grumphp#260]
| Q               | A
| --------------- | ---
| Question?       | yes

When GrumPHP scans the code prior to commit, what exactly does it scan?

- [ ] The whole project
- [ ] Only changed files
- [ ] Only changed lines

**Comment by jyggen** [comment]
When running `./vendor/bin/grumphp run` all files in the repository are checked and during the pre-commit hook iIt depends on the task. Most tasks (afaik) only check changed files but some tasks (`phpcpd` for example) will scan the whole project since it wouldn't be that useful otherwise.

**Comment by veewee** [comment]
Indeed:
- run: Checks all files committed in git
- pre-commit + commit-msg: Checks only the changed files

Most taks work directly with these files, but there are some commands like `git_blacklist` that are able to check only the commited lines. It's up to the task to determine what exactly is being used.

In a future version it will also be possible to hook in on the pre-puss hook. This will check a list of transfered files (hopefully :) ).

the feedback on this issue will be added to the documentation. In the meantime, I created #265 to keep track on this change. I'll close this issue for now.
