### ISSUE TITLE
What is the easiest way to bypass GrumPHP?

### ISSUE THREAD

**Issue by Bilge** [phpro/grumphp#261]
| Q               | A
| --------------- | ---
| Question?       | yes

Although we would want most people to respect GrumPHP most of the time, exceptions must apply. What is the easiest way to temporarily bypass GrumPHP if it is not desired?

**Comment by jyggen** [comment]
Use the `--no-verify` (`-n`) flag when you commit which bypasses the pre-commit and commit-msg hooks.

**Comment by veewee** [comment]
As @jyggen mentioned, you can bypass GrumPHP by using the `-n` flag in git.
Another option is to remove the git hooks. There is also the command `git:deinit`.

the feedback on this issue will be added to the documentation. In the meantime, I created #265 to keep track on this change. I'll close this issue for now.
