### ISSUE TITLE
Installation fails on Windows 7/WINGW with symlinked directories.

### ISSUE THREAD

**Issue by Bilge** [phpro/grumphp#283]
| Q               | A
| --------------- | ---
| Branch          |  v0.11.1 
| Bug?            | yes
| New feature?    | no
| Question?       | no
| Documentation?  | no
| Related tickets | n/a

**My configuration**
Generated by the installer in `D:\api\grumphp.yml`.
```yaml
parameters:
    git_dir: '../../../../../../D:/api'
    bin_dir: vendor/bin
    tasks: {  }
```

**Steps to reproduce:**
```sh
composer require --dev 'phpro/grumphp ^0|^1'
```

**Result:**
>GrumPHP can not sniff your commits. Did you specify the correct git-dir?
PHP Fatal error:  Uncaught exception 'Gitonomy\Git\Exception\InvalidArgumentException' with message 'Directory "" does not exist or is not a directory' in D:\Users\e\f\g\api\vendor\gitonomy\gitlib\src\Gitonomy\Git\Repository.php:158
Stack trace:
#0 D:\Users\e\f\g\api\vendor\gitonomy\gitlib\src\Gitonomy\Git\Repository.php(131): Gitonomy\Git\Repository->initDir('../../../../../...', NULL)
#1 [internal function]: Gitonomy\Git\Repository->__construct('../../../../../...', Array)
#2 D:\Users\e\f\g\api\vendor\symfony\dependency-injection\ContainerBuilder.php(892): ReflectionClass->newInstanceArgs(Array)
#3 D:\Users\e\f\g\api\vendor\symfony\dependency-injection\ContainerBuilder.php(443): Symfony\Component\DependencyInjection\ContainerBuilder->createService(Object(Symfony\Component\DependencyInjection\Definition), 'git.repository')
#4 D:\Users\e\f\g\api\vendor\phpro\grumphp\src\Grum in D:\Users\e\f\g\api\vendor\gitonomy\gitlib\src\Gitonomy\Git\Repository.php on line 158

**Observation:**
It seems GrumPHP creates an invalid configuration on Windows 7.

`$ pwd
/c/Users/e/f/g/api`

It seems that because my `c:\Users` is symlinked to `d:\Users`, it backtracks all the way to the root directory to walk back the same path on the D: drive. However bizarre this is, it should work, except that it wrote `D:` instead of just `D`. MINGW strips off the colon when resolving Windows drive letters.

Even if I fix the config so GrumPHP can run, its commands still fail in the same way for the same reason.

>$ vendor/bin/grumphp git:init
>
>  [Symfony\Component\Filesystem\Exception\IOException]
  Failed to create "../../../../../../D:/Users/e/f/g/api/.git/hooks/": mkdir(): Invalid argument.

However, if I `cd /d/e/f/g/api`, it works fine because it doesn't backtrack through the root directory to reach the `D` drive any more.

>$ vendor/bin/grumphp git:init
Watch out! GrumPHP is sniffing your commits!

**Comment by veewee** [comment]
Thanks for reporting! Some of the paths are translated with `realpath()` before they are converted to relative paths. This might cause the error, but won't be easy to fix. 
Also: The committed files are directly transfered to the subcommands. So is this an issue with GrumPHP or an issue in all the tasks?

**Comment by Bilge** [comment]
>is this an issue with GrumPHP or an issue in all the tasks?

I believe it's an issue with GrumPHP, since as demonstrated, the `git:init` command fails in the same way.

Conventional wisdom suggests `realpath()` should be avoided, if only because it does not work in PHARs. It is probable you will never ship GrumPHP this way since it is a Composer plugin, but avoiding `realpath()` might also help alleviate this issue.

**Comment by veewee** [comment]
Indeed... I am not sure why it was added, but it surely was for some reason. 
If we want to support phar (#61), we will need to fix this anyway.

**Comment by veewee** [comment]
Since the path system got a rewrite in #644 which supports symlinks better, I am closing this issue for now.
Feel free to test that PR out and validate if it still works on your environment.
A new release will follow soon-ish.
Feel free to open up a new issue if this PR doesn't solve this issue for you.
