### ISSUE TITLE
Local repository checkout will not run GrumPHP binary on Windows

### ISSUE THREAD

**Issue by Bilge** [phpro/grumphp#295]
| Q               | A
| --------------- | ---
| Branch          | ???
| Bug?            | yes
| New feature?    | no
| Question?       | no
| Documentation?  | no
| Related tickets | symfony/symfony#21613

The first issue is that the `grumphp.yml.dist` specifies `bin_dir: "./vendor/bin"`, but the binary is in `bin` for a local checkout. However, even when specifying, `bin_dir: bin`, `ExternalCommand::locate` still fails to find the binary.

The second issue is that `ExecutableFinder` assumes all executables must have a suffix on a Windows system. On my system it is searching for `.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.RB;.RBW` but we know the `grumphp` binary has no extension, so it never finds it!

These issues can be tested my merely checking out the repository on a Windows system and attempting to run `bin/grumphp git:init`.

**Comment by veewee** [comment]
Nice catch. I've had this package installed from day one. Therefor I always had a working git hook locally.
We should add some composer hook that automatically registers the git hook to your system.

At the moment, you can create a symbolic link to the vendor/bin folder manually:
 
```sh
ln -s ../../bin/grumphp vendor/bin/grumphp
./vendor/bin/grumphp git:init
```

**Comment by Bilge** [comment]
@veewee Unfortunately I do not understand your reply at all. Did you mean to leave this on a different ticket? The second issue isn't really a GrumPHP issue; it's a Symfony/Process issue as specified in the *related tickets* section.

Regarding the first issue, symlinking isn't necessary because we can just copy the `grumphp.yml.dist` to `grumphp.yml` and set `bin_dir: bin`. This tends to be a better solution because we probably want to customize other settings anyway and symlinking tends to be hard on Windows.

**Comment by veewee** [comment]
@Bilge: You don't want to set the bin_dir to bin because you won't be able to detect the other executables in the vendor/bin directory. Like e.g. phpspec, phpcs, ...
It will fall back to your global installed executables if they exist, but won't be able to detect the application specific executables.

The way I see it, grumphp should be configured during the installation of composer withouth any manual actions.

**Comment by Bilge** [comment]
Ah, I think I understand now!

>The way I see it, grumphp should be configured during the installation of composer withouth any manual actions.

Are you thinking in terms of a Composer script event, such as `post-install-cmd`?

**Comment by veewee** [comment]
@Bilge: Indeed. I've added a composer script that registers during install / update of the root package. This will ensure that all people developing on this package also have a working git hook. For now a hard copy looks more then sufficient.
I see that the executable finder PR has been merged. I am closing this issue for now.
