### ISSUE TITLE
Why is GrumPHP so kawaii?

### ISSUE THREAD

**Issue by Bilge** [phpro/grumphp#321]
:thinking:

**Comment by veewee** [comment]
I also asked myself that question ... In fact, I asked 100 peoples opinion. Here is their reaction:

![Dont know...](https://media0.giphy.com/media/26ufc0OsEUTWhDw0E/200.gif#0)![Dont know...](https://media3.giphy.com/media/130d6vlmqNcqxG/200.gif#1)![Dont know...](https://media4.giphy.com/media/Q25XQvcPhghRS/200.gif#2)![Dont know...](https://media4.giphy.com/media/3o7TKt8QwslhfRsHNC/200.gif#3)![Dont know...](https://media1.giphy.com/media/26Do7OCsOh2YKmjgA/200w.gif#4)![Dont know...](https://media4.giphy.com/media/l0HlA7i5qTFedPFK0/200w.gif#5)![Dont know...](https://media3.giphy.com/media/26gst8hEVQzQpzJDy/200.gif#6)![Dont know...](https://media1.giphy.com/media/3oz8xz12gyjTolxSYo/200w.gif#7)![Dont know...](https://media2.giphy.com/media/3o7TKrzgLkN5DwWNOg/200w.gif#8)![Dont know...](https://media4.giphy.com/media/l2YStk7mpUSfVyaju/200.gif#9)![Dont know...](https://media0.giphy.com/media/3o6ZsSNMMBsrZMzLC8/200.gif#10)![Dont know...](https://media2.giphy.com/media/l0CRB8G9P50ux7qx2/200.gif#11)![Dont know...](https://media0.giphy.com/media/xT0GqemvHG1ebwRGyA/200.gif#12)![Dont know...](https://media4.giphy.com/media/xT8qBioEPP8w3Pji6c/200.gif#13)![Dont know...](https://media3.giphy.com/media/l2SqaDYyBLKQULGMM/200.gif#14)![Dont know...](https://media3.giphy.com/media/3o6ZtljByvs2JPPEAM/200.gif#15)![Dont know...](https://media3.giphy.com/media/1ArwrVnL5voAM/200.gif#16)![Dont know...](https://media0.giphy.com/media/pveCsgUX44x7a/200.gif#17)![Dont know...](https://media4.giphy.com/media/Yo3ubsWFpJc9q/200.gif#18)![Dont know...](https://media0.giphy.com/media/5aQzOYHvSr9io/200.gif#19)![Dont know...](https://media4.giphy.com/media/KZik8L1xW5IxW/200.gif#20)![Dont know...](https://media2.giphy.com/media/26BkLAToA4UWupVKw/200w.gif#21)![Dont know...](https://media0.giphy.com/media/l2JdVMo9TPXyOFec8/200.gif#22)![Dont know...](https://media4.giphy.com/media/l2Jegww9uEVCJWotq/200.gif#23)![Dont know...](https://media2.giphy.com/media/l0G182smzwcmKhD7q/200.gif#24)![Dont know...](https://media3.giphy.com/media/3o6Mbe4WBbmNUo2LLO/200.gif#25)![Dont know...](https://media2.giphy.com/media/tO5ddHjpXB6lG/200.gif#26)![Dont know...](https://media3.giphy.com/media/xTiTnd71eSgC68wwCc/200.gif#27)![Dont know...](https://media4.giphy.com/media/riATx4iHMU1LW/200.gif#28)![Dont know...](https://media3.giphy.com/media/cd1fKObMEyDtK/200.gif#29)![Dont know...](https://media0.giphy.com/media/kt23tKB8dXthS/200.gif#30)![Dont know...](https://media3.giphy.com/media/13s8UKEHbMWFEs/200.gif#31)![Dont know...](https://media2.giphy.com/media/10DCNyJUVAoITu/200.gif#32)![Dont know...](https://media0.giphy.com/media/5W4pgiavuuTLO/200.gif#33)![Dont know...](https://media4.giphy.com/media/3o7btW6jvrZduOA3ZK/200.gif#34)![Dont know...](https://media0.giphy.com/media/OtBgrMheb5m2A/200.gif#35)![Dont know...](https://media2.giphy.com/media/3orifdobAeepwzxsWs/200.gif#36)![Dont know...](https://media3.giphy.com/media/3oz8xzm1jW9Nd6TqfK/200.gif#37)![Dont know...](https://media3.giphy.com/media/l3q2DN1zmiNlWUl8Y/200.gif#38)![Dont know...](https://media4.giphy.com/media/l0Exr8SPeBwE4o5kk/200.gif#39)![Dont know...](https://media3.giphy.com/media/3o7aTlAhsx5wNVh4Dm/200.gif#40)![Dont know...](https://media1.giphy.com/media/3oz8xMue6At1vUhTq0/200.gif#41)![Dont know...](https://media2.giphy.com/media/xTiN0Pf6nAhHeV94ty/200.gif#42)![Dont know...](https://media1.giphy.com/media/l3vRhezXf4cjzYXFS/200.gif#43)![Dont know...](https://media2.giphy.com/media/l0HlxbPap7AC0VjMs/200.gif#44)![Dont know...](https://media3.giphy.com/media/3o6ZtdmjXxchXJqxHO/200.gif#45)![Dont know...](https://media4.giphy.com/media/l41YBu8vgBGUHmGGI/200.gif#46)![Dont know...](https://media2.giphy.com/media/l1AvzOcybgkRFy5gI/200.gif#47)![Dont know...](https://media1.giphy.com/media/3ohfFHkmMci57UJa5G/200.gif#48)![Dont know...](https://media2.giphy.com/media/l0MYRacWiUSxR2JMc/200.gif#49)![Dont know...](https://media1.giphy.com/media/xTka03VK5vUWTjBrsA/200.gif#50)![Dont know...](https://media2.giphy.com/media/bkKvvzE9PEcTK/200.gif#51)![Dont know...](https://media3.giphy.com/media/N97IIOarXMMc8/200.gif#52)![Dont know...](https://media0.giphy.com/media/FUQgB5l7w6Ij6/200.gif#53)![Dont know...](https://media4.giphy.com/media/9w3w4eP5ZUgiQ/200.gif#54)![Dont know...](https://media3.giphy.com/media/l0MYMJFkVrIjiRiJW/200.gif#55)![Dont know...](https://media3.giphy.com/media/l3vR5utIOimdDnhBK/200.gif#56)![Dont know...](https://media1.giphy.com/media/3oz8xGvb3YXCFKd3zy/200.gif#57)![Dont know...](https://media2.giphy.com/media/3o7TKtA4CoVqVn0oKI/200.gif#58)![Dont know...](https://media4.giphy.com/media/3oz8xEHtiMGzgRy8EM/200.gif#59)![Dont know...](https://media2.giphy.com/media/3o7TKRAK6hHAmiiQZq/200.gif#60)![Dont know...](https://media2.giphy.com/media/3o7TKzF6jCTPlEpo1a/200.gif#61)![Dont know...](https://media1.giphy.com/media/3oz8xvIhwMiz5nJsCQ/200.gif#62)![Dont know...](https://media0.giphy.com/media/l3vR6LjBXWs3vtBUQ/200.gif#63)![Dont know...](https://media2.giphy.com/media/3o7TKwziXByKr8HMkw/200.gif#64)![Dont know...](https://media4.giphy.com/media/3o7TKux9sStVmYab9S/200.gif#65)![Dont know...](https://media2.giphy.com/media/l0MYHehcrQde6jGW4/200.gif#66)![Dont know...](https://media3.giphy.com/media/l0MYM5sPlf5gsVMTS/200.gif#67)![Dont know...](https://media3.giphy.com/media/3o7TKT5AWER3HlJvYQ/200.gif#68)![Dont know...](https://media1.giphy.com/media/l0MYDTbY6vH7LDneE/200.gif#69)![Dont know...](https://media1.giphy.com/media/3oz8xT7vIbuLGhmCze/200.gif#70)![Dont know...](https://media0.giphy.com/media/l0MYAWIUsnC7Z3a00/200.gif#71)![Dont know...](https://media0.giphy.com/media/3o7TKKs2T31vwyFFOE/200.gif#72)![Dont know...](https://media1.giphy.com/media/3o7TKR1oyeSawq638k/200.gif#73)![Dont know...](https://media0.giphy.com/media/3oz8xISxk6FBPNNHmo/200.gif#74)![Dont know...](https://media1.giphy.com/media/3o7TKqvLZRlAzlA62s/200.gif#75)![Dont know...](https://media4.giphy.com/media/3o7TKzKEOZ6SmwRyCI/200.gif#76)![Dont know...](https://media0.giphy.com/media/bYBbM6iFTfdHa/200.gif#77)![Dont know...](https://media1.giphy.com/media/3otPopxmGPEkjpF4t2/200.gif#78)![Dont know...](https://media2.giphy.com/media/3o7TKwaT68QOObzy2A/200.gif#79)![Dont know...](https://media2.giphy.com/media/l0MYSfUZGC7bdGCqY/200.gif#80)![Dont know...](https://media0.giphy.com/media/l0MYSwZNUZyqihnX2/200.gif#81)![Dont know...](https://media0.giphy.com/media/l3vQYFtOdZlopbRSw/200.gif#82)![Dont know...](https://media3.giphy.com/media/3o7TKCsqdptRSDLT4Q/200.gif#83)![Dont know...](https://media1.giphy.com/media/3oz8xRA7KVJP3ocUtq/200.gif#84)![Dont know...](https://media0.giphy.com/media/3oz8xtZLddHGGQt0Na/200.gif#85)![Dont know...](https://media3.giphy.com/media/3oz8xEFgC6FAStUO5O/200.gif#86)![Dont know...](https://media1.giphy.com/media/l0MYxbzPuHoiVCVTG/200.gif#87)![Dont know...](https://media3.giphy.com/media/3o7TKMK1oQITBWMWwo/200.gif#88)![Dont know...](https://media1.giphy.com/media/3o7TKKwJKSoOm9HG5G/200.gif#89)![Dont know...](https://media2.giphy.com/media/3o7TKRS6kCHxrad4KQ/200.gif#90)![Dont know...](https://media0.giphy.com/media/3o7TKoGpjEZz39YB7G/200.gif#91)![Dont know...](https://media2.giphy.com/media/l0MYP768Ulg37wK2Y/200.gif#92)![Dont know...](https://media3.giphy.com/media/l3vRhJ3koBZ1K5WIo/200.gif#93)![Dont know...](https://media1.giphy.com/media/3oz8xWDUYAGLaU92Gk/200.gif#94)![Dont know...](https://media2.giphy.com/media/l3vRgZfpK0a1CKBtm/200.gif#95)![Dont know...](https://media2.giphy.com/media/l3vQXxNiVuIdAf6fu/200.gif#96)![Dont know...](https://media4.giphy.com/media/l4Jz46I28lRfjzR96/200.gif#97)![Dont know...](https://media4.giphy.com/media/l3vRiGJzSIg7OoiWI/200.gif#98)![Dont know...](https://media1.giphy.com/media/3o6ZtdqXa3uFyMW3nO/200.gif#99)

**Comment by Bilge** [comment]
Some of those peoples seem to be the same peoples so I'd like to conjecture that, in fact, the total number of peoples surveyed may be less than the purported 100 you so claim.
