### ISSUE TITLE
Add "Check for fully qualified function calls" task

### ISSUE THREAD

**Issue by veewee** [phpro/grumphp#325]
| Q               | A
| --------------- | ---
| Bug?            | yes
| New feature?    | yes
| Question?       | no
| Documentation?  | no
| Related tickets | #

More info: http://veewee.github.io/blog/optimizing-php-performance-by-fq-function-calls/
CLI tool: https://github.com/kelunik/fqn-check
Other possibility: Convert the node visitor in the cli tool above to a new [GrumPGP php_parser Visitor](https://github.com/phpro/grumphp/blob/master/doc/tasks/phpparser.md#creating-your-own-visitor).

**Comment by patkar** [comment]
Exists as `native_function_invocation` rule in PHP-CS-Fixer too

**Comment by veewee** [comment]
Closing this issue since it is implemented in php-cs-fixer.
