### ISSUE TITLE
Get it running with vagrant

### ISSUE THREAD

**Issue by luemic** [phpro/grumphp#326]
| Q               | A
| --------------- | ---
| Version         | `0.11.1`
| Bug?            | no
| New feature?    | no
| Question?       | yes
| Documentation?  | no

Hi guys,

how do I setup grumphp to run in a vagrant box. In my case I use Laravel homestead, which is located in the /homestead folder within my project. When I set hooks_preset to vagrant I got following error:
```
A Vagrant environment or target machine is required to run this
			command. Run `vagrant init` to create a new Vagrant environment. Or,
			get an ID of a target machine from `vagrant global-status` to run
			this command on. A final option is to change to a directory with a
			Vagrantfile and to try again.
```

What am I missing?

Kind regards

Michael

**Comment by veewee** [comment]
Hi @luemic,

Currently this is not possible with the default git hooks. You can define your own preset files for this structure untill it is possible to add configurable options to the hooks.

More info:
https://github.com/phpro/grumphp/issues/153
