### ISSUE TITLE
Validate Git branch naming convention

### ISSUE THREAD

**Issue by ademarco** [phpro/grumphp#328]
| Q               | A
| --------------- | ---
| Version         | `0.11.3`
| Bug?            | no
| New feature?    | yes
| Question?       | yes
| Documentation?  | no
| Related tickets | 

In my organisation we need to enforce specific Git branch naming conventions so I was wondering if this is something GrumPHP could take care of.

I've been sneaking around the code and it looks like we could leverage the `\Gitonomy\Git\Reference\Branch` class to gather information about the current branch and validate it using regular expressions, like the commit message task currently does.

Would this be something interesting for GrumPHP? In case it would be we could dedicate some time to it.

**Comment by drupol** [comment]
👍

**Comment by netlooker** [comment]
👍

**Comment by veewee** [comment]
👍 That would be a nice addition. Feel free to implement.

**Comment by ademarco** [comment]
Ok PR is ready for review!

**Comment by veewee** [comment]
Implemented in #329.
