### ISSUE TITLE
Custom config.yml path at composer.json file extras

### ISSUE THREAD

**Issue by igormukhingmailcom** [phpro/grumphp#36]
Hi guys.

That would be great if we can write some parameter at `composer.json` file extras that will be used at `grumphp` when it installed via `composer install` or added via `composer require`.

Something like this:
```
{
    "extra": {
        "grumphp": {
            "config-default-path": "vendor/our/package/path/to/config.yml"
        }
    }
}
```

Lets discuss and I will implement this.
Thanks.

**Comment by igormukhingmailcom** [comment]
Why this will be helpful for me and others?
A lot of companies have its own conventions and need to have code-style checker on pre-commit hook.
Your tool is best choice for this.
But as far as tool automatically installs `grumphp.yml` at project root path and make `git:init` with that path - its hard to override this behaviour and each user need to do next things again and again: https://github.com/linkorb/conventions-checker#installaion

**Comment by aderuwe** [comment]
I'm +1 on the feature, your use-case seems valid.
