### ISSUE TITLE
Why there are 2 versions of phpcsfixer?

### ISSUE THREAD

**Issue by poteirard** [phpro/grumphp#363]
| Q               | A
| --------------- | ---
| Version         | `grumphp -V`
| Bug?            | no
| New feature?    | no
| Question?       | yes
| Documentation?  | no
| Related tickets | -

It's a simple and a noob question but I was wondering... Why there are 2 versions of phpcsfixer ?
Should I use both? Any of them has any special capability?

Thanks

**Comment by veewee** [comment]
Hi @poteirard,

You don't need both tasks. v2 is just the latest version of php-cs-fixer which is not fully compatible with v1. I would suggest you to use v1.
As I saw in your config file in another issue: you don't need both the auto fixer and the fixer.
This package will never try to autofix before a commit. That functionality is provided by the auto fixer.

I hope this answers your question?

**Comment by poteirard** [comment]
Yes very well explained 👍 Thank you @veewee !
