### ISSUE TITLE
Lower symfony/console requirements for Magento 2 compatibility

### ISSUE THREAD

**Issue by Tjitse-E** [phpro/grumphp#372]
| Q               | A
| --------------- | ---
| Version         | `0.11.6`
| Bug?            | no
| New feature?    |no
| Question?       | yes
| Documentation?  |no
| Related tickets | 359

**Steps to reproduce:**
```sh
# Install Magento 2.1.7
composer require --dev phpro/grumphp
```

**Result:**
```sh
Using version ^0.11.6 for phpro/grumphp
./composer.json has been updated
Key magento/module-ui is a duplicate in ./composer.json at line 198
Gathering patches for root package.
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for phpro/grumphp ^0.11.6 -> satisfiable by phpro/grumphp[v0.11.6].
    - Conclusion: remove symfony/console v2.6.13
    - Conclusion: don't install symfony/console v2.6.13
    - phpro/grumphp v0.11.6 requires symfony/console ~2.7|~3.0 -> satisfiable by symfony/console[2.7.x-dev, 2.8.x-dev, 3.0.x-dev, 3.1.x-dev, 3.2.x-dev, 3.3.x-dev, 3.4.x-dev, v2.7.0, v2.7.0-BETA1, v2.7.0-BETA2, v2.7.1, v2.7.10, v2.7.11, v2.7.12, v2.7.13, v2.7.14, v2.7.15, v2.7.16, v2.7.17, v2.7.18, v2.7.19, v2.7.2, v2.7.20, v2.7.21, v2.7.22, v2.7.23, v2.7.24, v2.7.25, v2.7.26, v2.7.27, v2.7.28, v2.7.29, v2.7.3, v2.7.4, v2.7.5, v2.7.6, v2.7.7, v2.7.8, v2.7.9, v2.8.0, v2.8.0-BETA1, v2.8.1, v2.8.10, v2.8.11, v2.8.12, v2.8.13, v2.8.14, v2.8.15, v2.8.16, v2.8.17, v2.8.18, v2.8.19, v2.8.2, v2.8.20, v2.8.21, v2.8.22, v2.8.3, v2.8.4, v2.8.5, v2.8.6, v2.8.7, v2.8.8, v2.8.9, v3.0.0, v3.0.0-BETA1, v3.0.1, v3.0.2, v3.0.3, v3.0.4, v3.0.5, v3.0.6, v3.0.7, v3.0.8, v3.0.9, v3.1.0, v3.1.0-BETA1, v3.1.0-RC1, v3.1.1, v3.1.10, v3.1.2, v3.1.3, v3.1.4, v3.1.5, v3.1.6, v3.1.7, v3.1.8, v3.1.9, v3.2.0, v3.2.0-BETA1, v3.2.0-RC1, v3.2.0-RC2, v3.2.1, v3.2.2, v3.2.3, v3.2.4, v3.2.5, v3.2.6, v3.2.7, v3.2.8, v3.2.9, v3.3.0, v3.3.0-BETA1, v3.3.0-RC1, v3.3.1, v3.3.2].
```

The latest version of Magento 2 uses symfony/console 2.6, so i'm unable to install GrumPHP. I've lowered the GrumPHP requirements to `"symfony/console": "~2.6|~3.0"` to solve this problem. It doesn't seem to effect GrumPHP, so maybe we can lower the requirement?

**Comment by veewee** [comment]
Hi @Tjitse-E,

We've dropped 2.6 support in version 0.10 because the package isn't supported anymore since mid 2015:
![Symfony Support](http://symfony.com/doc/current/_images/release-process.jpg)

Since Symfony is not supporting this package anymore, I think we also shouldn't support it anymore.

During development we also noticed that Magento has many outdated packages. This makes it hard to write up-to-date tools that can also be used outside a Magento context.
We are currently fixing this by using something like this in the root composer.json file of the Magento project:

```json
"symfony/console": "v2.8.20 as v2.6.13",
```

Might this be a proper solution for you?

**Comment by Tjitse-E** [comment]
Yes, this seems to work. Thanks a lot @veewee!

**Comment by veewee** [comment]
No problem!

**Comment by sivajik34** [comment]
Cannot create cache directory /home/dcwlp24014/.composer/cache/repo/https---repo.magento.com/, or directory is not writable. Proceeding without cache
Cannot create cache directory /home/dcwlp24014/.composer/cache/repo/https---packagist.org/, or directory is not writable. Proceeding without cache
Cannot create cache directory /home/dcwlp24014/.composer/cache/files/, or directory is not writable. Proceeding without cache
Using version ^0.14.0 for phpro/grumphp
./composer.json has been updated
Cannot create cache directory /home/dcwlp24014/.composer/cache/repo/https---repo.magento.com/, or directory is not writable. Proceeding without cache
Cannot create cache directory /home/dcwlp24014/.composer/cache/repo/https---packagist.org/, or directory is not writable. Proceeding without cache
Cannot create cache directory /home/dcwlp24014/.composer/cache/files/, or directory is not writable. Proceeding without cache
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: remove symfony/console v2.8.34
    - Conclusion: don't install symfony/console v2.8.34
    - symfony/yaml v3.4.0 conflicts with symfony/console[v2.8.34].
    - symfony/yaml v3.4.1 conflicts with symfony/console[v2.8.34].
    - symfony/yaml v3.4.2 conflicts with symfony/console[v2.8.34].
    - symfony/yaml v3.4.3 conflicts with symfony/console[v2.8.34].
    - symfony/yaml v3.4.4 conflicts with symfony/console[v2.8.34].
    - symfony/yaml v3.4.5 conflicts with symfony/console[v2.8.34].
    - symfony/yaml v3.4.6 conflicts with symfony/console[v2.8.34].
    - symfony/yaml v3.4.7 conflicts with symfony/console[v2.8.34].
    - symfony/yaml v4.0.0 conflicts with symfony/console[v2.8.34].
    - symfony/yaml v4.0.1 conflicts with symfony/console[v2.8.34].
    - symfony/yaml v4.0.2 conflicts with symfony/console[v2.8.34].
    - symfony/yaml v4.0.3 conflicts with symfony/console[v2.8.34].
    - symfony/yaml v4.0.4 conflicts with symfony/console[v2.8.34].
    - symfony/yaml v4.0.5 conflicts with symfony/console[v2.8.34].
    - symfony/yaml v4.0.6 conflicts with symfony/console[v2.8.34].
    - symfony/yaml v4.0.7 conflicts with symfony/console[v2.8.34].
    - Installation request for symfony/console (locked at v2.8.34) -> satisfiable by symfony/console[v2.8.34].
    - Installation request for phpro/grumphp ^0.14.0 -> satisfiable by phpro/grumphp[v0.14.0].
    - Conclusion: don't install symfony/dependency-injection v3.4.4|install symfony/yaml v3.4.0|install symfony/yaml v3.4.1|install symfony/yaml v3.4.2|install symfony/yaml v3.4.3|install symfony/yaml v3.4.4|install symfony/yaml v3.4.5|install symfony/yaml v3.4.6|install symfony/yaml v3.4.7|install symfony/yaml v4.0.0|install symfony/yaml v4.0.1|install symfony/yaml v4.0.2|install symfony/yaml v4.0.3|install symfony/yaml v4.0.4|install symfony/yaml v4.0.5|install symfony/yaml v4.0.6|install symfony/yaml v4.0.7
    - Conclusion: remove symfony/dependency-injection v3.4.4|install symfony/yaml v3.4.0|install symfony/yaml v3.4.1|install symfony/yaml v3.4.2|install symfony/yaml v3.4.3|install symfony/yaml v3.4.4|install symfony/yaml v3.4.5|install symfony/yaml v3.4.6|install symfony/yaml v3.4.7|install symfony/yaml v4.0.0|install symfony/yaml v4.0.1|install symfony/yaml v4.0.2|install symfony/yaml v4.0.3|install symfony/yaml v4.0.4|install symfony/yaml v4.0.5|install symfony/yaml v4.0.6|install symfony/yaml v4.0.7
    - phpro/grumphp v0.14.0 requires symfony/yaml ~2.7|~3.0|~4.0 -> satisfiable by symfony/yaml[v2.7.0, v2.7.1, v2.7.10, v2.7.11, v2.7.12, v2.7.13, v2.7.14, v2.7.15, v2.7.16, v2.7.17, v2.7.18, v2.7.19, v2.7.2, v2.7.20, v2.7.21, v2.7.22, v2.7.23, v2.7.24, v2.7.25, v2.7.26, v2.7.27, v2.7.28, v2.7.29, v2.7.3, v2.7.30, v2.7.31, v2.7.32, v2.7.33, v2.7.34, v2.7.35, v2.7.36, v2.7.37, v2.7.38, v2.7.39, v2.7.4, v2.7.40, v2.7.41, v2.7.42, v2.7.43, v2.7.44, v2.7.5, v2.7.6, v2.7.7, v2.7.8, v2.7.9, v2.8.0, v2.8.1, v2.8.10, v2.8.11, v2.8.12, v2.8.13, v2.8.14, v2.8.15, v2.8.16, v2.8.17, v2.8.18, v2.8.19, v2.8.2, v2.8.20, v2.8.21, v2.8.22, v2.8.23, v2.8.24, v2.8.25, v2.8.26, v2.8.27, v2.8.28, v2.8.29, v2.8.3, v2.8.30, v2.8.31, v2.8.32, v2.8.33, v2.8.34, v2.8.35, v2.8.36, v2.8.37, v2.8.4, v2.8.5, v2.8.6, v2.8.7, v2.8.8, v2.8.9, v3.0.0, v3.0.1, v3.0.2, v3.0.3, v3.0.4, v3.0.5, v3.0.6, v3.0.7, v3.0.8, v3.0.9, v3.1.0, v3.1.1, v3.1.10, v3.1.2, v3.1.3, v3.1.4, v3.1.5, v3.1.6, v3.1.7, v3.1.8, v3.1.9, v3.2.0, v3.2.1, v3.2.10, v3.2.11, v3.2.12, v3.2.13, v3.2.14, v3.2.2, v3.2.3, v3.2.4, v3.2.5, v3.2.6, v3.2.7, v3.2.8, v3.2.9, v3.3.0, v3.3.1, v3.3.10, v3.3.11, v3.3.12, v3.3.13, v3.3.14, v3.3.15, v3.3.16, v3.3.2, v3.3.3, v3.3.4, v3.3.5, v3.3.6, v3.3.7, v3.3.8, v3.3.9, v3.4.0, v3.4.1, v3.4.2, v3.4.3, v3.4.4, v3.4.5, v3.4.6, v3.4.7, v4.0.0, v4.0.1, v4.0.2, v4.0.3, v4.0.4, v4.0.5, v4.0.6, v4.0.7].
    - symfony/yaml v2.7.0 conflicts with symfony/dependency-injection[v3.4.4].
    - symfony/yaml v2.7.1 conflicts with symfony/dependency-injection[v3.4.4].
    - symfony/yaml v2.7.10 conflicts with symfony/dependency-injection[v3.4.4].
    - symfony/yaml v2.7.11 conflicts with symfony/dependency-injection[v3.4.4].
    - symfony/yaml v2.7.12 conflicts with symfony/dependency-injection[v3.4.4].
    - symfony/yaml v2.7.13 conflicts with symfony/dependency-injection[v3.4.4].
    - symfony/yaml v2.7.14 conflicts with symfony/dependency-injection[v3.4.4].
    - symfony/yaml v2.7.15 conflicts with symfony/dependency-injection[v3.4.4].
    - symfony/yaml v2.7.16 conflicts with symfony/dependency-injection[v3.4.4].
    - symfony/yaml v2.7.17 conflicts with symfony/dependency-injection[v3.4.4].
    - symfony/yaml v2.7.18 conflicts with symfony/dependency-injection[v3.4.4].
    - symfony/yaml v2.7.19 conflicts with symfony/dependency-injection[v3.4.4].
    - symfony/yaml v2.7.2 conflicts with symfony/dependency-injection[v3.4.4].
    - symfony/yaml v2.7.20 conflicts with symfony/dependency-injection[v3.4.4].
    - symfony/yaml v2.7.21 conflicts with symfony/dependency-injection[v3.4.4].
    - symfony/yaml v2.7.22 conflicts with symfony/dependency-injection[v3.4.4].
    - symfony/yaml v2.7.23 conflicts with symfony/dependency-injection[v3.4.4].
    - symfony/yaml v2.7.24 conflicts with symfony/dependency-injection[v3.4.4].
    - symfony/yaml v2.7.25 conflicts with symfony/dependency-injection[v3.4.4].
    - symfony/yaml v2.7.26 conflicts with symfony/dependency-injection[v3.4.4].
    - symfony/yaml v2.7.27 conflicts with symfony/dependency-injection[v3.4.4].
    - symfony/yaml v2.7.28 conflicts with symfony/dependency-injection[v3.4.4].
    - symfony/yaml v2.7.29 conflicts with symfony/dependency-injection[v3.4.4].
    - symfony/yaml v2.7.3 conflicts with symfony/dependency-injection[v3.4.4].
    - symfony/yaml v2.7.30 conflicts with symfony/dependency-injection[v3.4.4].
    - symfony/yaml v2.7.31 conflicts with symfony/dependency-injection[v3.4.4].
    - symfony/yaml v2.7.32 conflicts with symfony/dependency-injection[v3.4.4].
    - symfony/yaml v2.7.33 conflicts with symfony/dependency-injection[v3.4.4].
    - symfony/yaml v2.7.34 conflicts with symfony/dependency-injection[v3.4.4].
    - symfony/yaml v2.7.35 conflicts with symfony/dependency-injection[v3.4.4].
    - symfony/yaml v2.7.36 conflicts with symfony/dependency-injection[v3.4.4].
    - symfony/yaml v2.7.37 conflicts with symfony/dependency-injection[v3.4.4].
    - symfony/yaml v2.7.38 conflicts with symfony/dependency-injection[v3.4.4].
    - symfony/yaml v2.7.39 conflicts with symfony/dependency-injection[v3.4.4].
    - symfony/yaml v2.7.4 conflicts with symfony/dependency-injection[v3.4.4].
    - symfony/yaml v2.7.40 conflicts with symfony/dependency-injection[v3.4.4].
    - symfony/yaml v2.7.41 conflicts with symfony/dependency-injection[v3.4.4].
    - symfony/yaml v2.7.42 conflicts with symfony/dependency-injection[v3.4.4].
    - symfony/yaml v2.7.43 conflicts with symfony/dependency-injection[v3.4.4].
    - symfony/yaml v2.7.44 conflicts with symfony/dependency-injection[v3.4.4].
    - symfony/yaml v2.7.5 conflicts with symfony/dependency-injection[v3.4.4].
    - symfony/yaml v2.7.6 conflicts with symfony/dependency-injection[v3.4.4].
    - symfony/yaml v2.7.7 conflicts with symfony/dependency-injection[v3.4.4].
    - symfony/yaml v2.7.8 conflicts with symfony/dependency-injection[v3.4.4].
    - symfony/yaml v2.7.9 conflicts with symfony/dependency-injection[v3.4.4].
    - symfony/yaml v2.8.0 conflicts with symfony/dependency-injection[v3.4.4].
    - symfony/yaml v2.8.1 conflicts with symfony/dependency-injection[v3.4.4].
    - symfony/yaml v2.8.10 conflicts with symfony/dependency-injection[v3.4.4].
    - symfony/yaml v2.8.11 conflicts with symfony/dependency-injection[v3.4.4].
    - symfony/yaml v2.8.12 conflicts with symfony/dependency-injection[v3.4.4].
    - symfony/yaml v2.8.13 conflicts with symfony/dependency-injection[v3.4.4].
    - symfony/yaml v2.8.14 conflicts with symfony/dependency-injection[v3.4.4].
    - symfony/yaml v2.8.15 conflicts with symfony/dependency-injection[v3.4.4].
    - symfony/yaml v2.8.16 conflicts with symfony/dependency-injection[v3.4.4].
    - symfony/yaml v2.8.17 conflicts with symfony/dependency-injection[v3.4.4].
    - symfony/yaml v2.8.18 conflicts with symfony/dependency-injection[v3.4.4].
    - symfony/yaml v2.8.19 conflicts with symfony/dependency-injection[v3.4.4].
    - symfony/yaml v2.8.2 conflicts with symfony/dependency-injection[v3.4.4].
    - symfony/yaml v2.8.20 conflicts with symfony/dependency-injection[v3.4.4].
    - symfony/yaml v2.8.21 conflicts with symfony/dependency-injection[v3.4.4].
    - symfony/yaml v2.8.22 conflicts with symfony/dependency-injection[v3.4.4].
    - symfony/yaml v2.8.23 conflicts with symfony/dependency-injection[v3.4.4].
    - symfony/yaml v2.8.24 conflicts with symfony/dependency-injection[v3.4.4].
    - symfony/yaml v2.8.25 conflicts with symfony/dependency-injection[v3.4.4].
    - symfony/yaml v2.8.26 conflicts with symfony/dependency-injection[v3.4.4].
    - symfony/yaml v2.8.27 conflicts with symfony/dependency-injection[v3.4.4].
    - symfony/yaml v2.8.28 conflicts with symfony/dependency-injection[v3.4.4].
    - symfony/yaml v2.8.29 conflicts with symfony/dependency-injection[v3.4.4].
    - symfony/yaml v2.8.3 conflicts with symfony/dependency-injection[v3.4.4].
    - symfony/yaml v2.8.30 conflicts with symfony/dependency-injection[v3.4.4].
    - symfony/yaml v2.8.31 conflicts with symfony/dependency-injection[v3.4.4].
    - symfony/yaml v2.8.32 conflicts with symfony/dependency-injection[v3.4.4].
    - symfony/yaml v2.8.33 conflicts with symfony/dependency-injection[v3.4.4].
    - symfony/yaml v2.8.34 conflicts with symfony/dependency-injection[v3.4.4].
    - symfony/yaml v2.8.35 conflicts with symfony/dependency-injection[v3.4.4].
    - symfony/yaml v2.8.36 conflicts with symfony/dependency-injection[v3.4.4].
    - symfony/yaml v2.8.37 conflicts with symfony/dependency-injection[v3.4.4].
    - symfony/yaml v2.8.4 conflicts with symfony/dependency-injection[v3.4.4].
    - symfony/yaml v2.8.5 conflicts with symfony/dependency-injection[v3.4.4].
    - symfony/yaml v2.8.6 conflicts with symfony/dependency-injection[v3.4.4].
    - symfony/yaml v2.8.7 conflicts with symfony/dependency-injection[v3.4.4].
    - symfony/yaml v2.8.8 conflicts with symfony/dependency-injection[v3.4.4].
    - symfony/yaml v2.8.9 conflicts with symfony/dependency-injection[v3.4.4].
    - symfony/yaml v3.0.0 conflicts with symfony/dependency-injection[v3.4.4].
    - symfony/yaml v3.0.1 conflicts with symfony/dependency-injection[v3.4.4].
    - symfony/yaml v3.0.2 conflicts with symfony/dependency-injection[v3.4.4].
    - symfony/yaml v3.0.3 conflicts with symfony/dependency-injection[v3.4.4].
    - symfony/yaml v3.0.4 conflicts with symfony/dependency-injection[v3.4.4].
    - symfony/yaml v3.0.5 conflicts with symfony/dependency-injection[v3.4.4].
    - symfony/yaml v3.0.6 conflicts with symfony/dependency-injection[v3.4.4].
    - symfony/yaml v3.0.7 conflicts with symfony/dependency-injection[v3.4.4].
    - symfony/yaml v3.0.8 conflicts with symfony/dependency-injection[v3.4.4].
    - symfony/yaml v3.0.9 conflicts with symfony/dependency-injection[v3.4.4].
    - symfony/yaml v3.1.0 conflicts with symfony/dependency-injection[v3.4.4].
    - symfony/yaml v3.1.1 conflicts with symfony/dependency-injection[v3.4.4].
    - symfony/yaml v3.1.10 conflicts with symfony/dependency-injection[v3.4.4].
    - symfony/yaml v3.1.2 conflicts with symfony/dependency-injection[v3.4.4].
    - symfony/yaml v3.1.3 conflicts with symfony/dependency-injection[v3.4.4].
    - symfony/yaml v3.1.4 conflicts with symfony/dependency-injection[v3.4.4].
    - symfony/yaml v3.1.5 conflicts with symfony/dependency-injection[v3.4.4].
    - symfony/yaml v3.1.6 conflicts with symfony/dependency-injection[v3.4.4].
    - symfony/yaml v3.1.7 conflicts with symfony/dependency-injection[v3.4.4].
    - symfony/yaml v3.1.8 conflicts with symfony/dependency-injection[v3.4.4].
    - symfony/yaml v3.1.9 conflicts with symfony/dependency-injection[v3.4.4].
    - symfony/yaml v3.2.0 conflicts with symfony/dependency-injection[v3.4.4].
    - symfony/yaml v3.2.1 conflicts with symfony/dependency-injection[v3.4.4].
    - symfony/yaml v3.2.10 conflicts with symfony/dependency-injection[v3.4.4].
    - symfony/yaml v3.2.11 conflicts with symfony/dependency-injection[v3.4.4].
    - symfony/yaml v3.2.12 conflicts with symfony/dependency-injection[v3.4.4].
    - symfony/yaml v3.2.13 conflicts with symfony/dependency-injection[v3.4.4].
    - symfony/yaml v3.2.14 conflicts with symfony/dependency-injection[v3.4.4].
    - symfony/yaml v3.2.2 conflicts with symfony/dependency-injection[v3.4.4].
    - symfony/yaml v3.2.3 conflicts with symfony/dependency-injection[v3.4.4].
    - symfony/yaml v3.2.4 conflicts with symfony/dependency-injection[v3.4.4].
    - symfony/yaml v3.2.5 conflicts with symfony/dependency-injection[v3.4.4].
    - symfony/yaml v3.2.6 conflicts with symfony/dependency-injection[v3.4.4].
    - symfony/yaml v3.2.7 conflicts with symfony/dependency-injection[v3.4.4].
    - symfony/yaml v3.2.8 conflicts with symfony/dependency-injection[v3.4.4].
    - symfony/yaml v3.2.9 conflicts with symfony/dependency-injection[v3.4.4].
    - symfony/yaml v3.3.0 conflicts with symfony/dependency-injection[v3.4.4].
    - symfony/yaml v3.3.1 conflicts with symfony/dependency-injection[v3.4.4].
    - symfony/yaml v3.3.10 conflicts with symfony/dependency-injection[v3.4.4].
    - symfony/yaml v3.3.11 conflicts with symfony/dependency-injection[v3.4.4].
    - symfony/yaml v3.3.12 conflicts with symfony/dependency-injection[v3.4.4].
    - symfony/yaml v3.3.13 conflicts with symfony/dependency-injection[v3.4.4].
    - symfony/yaml v3.3.14 conflicts with symfony/dependency-injection[v3.4.4].
    - symfony/yaml v3.3.15 conflicts with symfony/dependency-injection[v3.4.4].
    - symfony/yaml v3.3.16 conflicts with symfony/dependency-injection[v3.4.4].
    - symfony/yaml v3.3.2 conflicts with symfony/dependency-injection[v3.4.4].
    - symfony/yaml v3.3.3 conflicts with symfony/dependency-injection[v3.4.4].
    - symfony/yaml v3.3.4 conflicts with symfony/dependency-injection[v3.4.4].
    - symfony/yaml v3.3.5 conflicts with symfony/dependency-injection[v3.4.4].
    - symfony/yaml v3.3.6 conflicts with symfony/dependency-injection[v3.4.4].
    - symfony/yaml v3.3.7 conflicts with symfony/dependency-injection[v3.4.4].
    - symfony/yaml v3.3.8 conflicts with symfony/dependency-injection[v3.4.4].
    - symfony/yaml v3.3.9 conflicts with symfony/dependency-injection[v3.4.4].
    - Installation request for symfony/dependency-injection (locked at v3.4.4) -> satisfiable by symfony/dependency-injection[v3.4.4].


Installation failed, reverting ./composer.json to its original content.

**Comment by torhoehn** [comment]
@veewee Where in composer.json should this be added?
`"symfony/console": "v2.8.20 as v2.6.13"`

**Comment by janvernieuwe** [comment]
Not a magento expert, but probably in require-dev, since grumphp is usually only required in dev.

**Comment by drazulay** [comment]
GrumPHP seems practically unsusable in Magento2 at the moment due to dependency conflicts. This is still an issue. The alias trick doesn't work either due to subdependencies.
