### ISSUE TITLE
Add file size check on commit

### ISSUE THREAD

**Issue by lykciv** [phpro/grumphp#374]
| Q               | A
| --------------- | ---
| Version         | -
| Bug?            | no
| New feature?    | yes
| Question?       | no
| Documentation?  | no
| Related tickets | -

Git does not cope well with big file sizes. I think it would be good if grumphp would stop you from trying to commit files over a certain size. 

I did a quick google and I found this, so I think it should be possible to implement this feature. I haven't tried it out yet myself:
https://stackoverflow.com/questions/39576257/how-to-limit-file-size-on-commit

**Comment by veewee** [comment]
Since we are using `SplFileObject`s internally, you can easily create a new task and check the `SplFileObject::getSize()` method for every file against a configurable maximum allowed filesize.

**Comment by Landerstraeten** [comment]
@veewee, you can assign this issue to me
