### ISSUE TITLE
[RFC] GitHook launch grumphp inside docker

### ISSUE THREAD

**Issue by Nek-** [phpro/grumphp#376]
| Q               | A
| --------------- | ---
| Version         | any
| Bug?            | no
| New feature?    | yes
| Question?       | no
| Documentation?  | no
| Related tickets | #152 

I'd like to point out that if the fact that grumphp configures alone git (which is awesome) it would be awesome if he could launch itself inside a docker when docker is present on the related system or executed inside a docker (idk if it's predictable).

Grump could ask (if docker detected) "would you like to run grumphp in a docker" then ask what's the name of the docker.

What do you think about? 🙂

**Comment by veewee** [comment]
We already discussed a lot of Docker stuff in #152. The idea is to make it possible to configure environment variables in the grumphp.yml file which will be available in the git hooks. This way it is possible to configure e.g. the docker container name.

Did you take a look at that issue yet?

**Comment by Nek-** [comment]
Mybad, duplicated :o !
