### ISSUE TITLE
Class 'GrumPHP\Console\Command\ConfigureCommand' not found

### ISSUE THREAD

**Issue by nWidart** [phpro/grumphp#381]
| Q               | A
| --------------- | ---
| Version         | `0.11.6`
| Bug?            | yes
| New feature?    | no
| Question?       | no
| Documentation?  | no

Hello,

I've just updated grumphp from 0.9, to 0.11, together with php-cs-fixer to version 2.

After running composer update, I received this output:

```
Writing lock file
Generating autoload files
ocramius/package-versions:  Generating version class...
ocramius/package-versions: ...done generating version class

                                                              
  [Symfony\Component\Debug\Exception\FatalThrowableError]     
  Class 'GrumPHP\Console\Command\ConfigureCommand' not found  
```

Was some change introduced requiring changes on our end?

Thank you,

**Comment by Kanti** [comment]
Does the error recur if you run ``composer update`` again?
See #300

**Comment by nWidart** [comment]
Oh thanks, it does indeed not recur on second composer update.

Thanks for your response, & sorry for the duplicate issue.
