### ISSUE TITLE
Removing GrumPHP

### ISSUE THREAD

**Issue by nWidart** [phpro/grumphp#384]
Hello,

I wanted to remove grumphp on a repository. However after removal, and committing the changed composer.json + removal of grumphp.yml file, I'm getting this error:

```
Commit failed with error
0 files committed, 2 files failed to commit: Removing grumphp
.git/hooks/pre-commit: line 12: /Users/nicolaswidart/Sites/Asguard/Extra-Modules/blog-block-app-20/Modules/Blog/vendor/phpro/grumphp/bin/grumphp: No such file or directory
.git/hooks/pre-commit: line 12: exec: /Users/nicolaswidart/Sites/Asguard/Extra-Modules/blog-block-app-20/Modules/Blog/vendor/phpro/grumphp/bin/grumphp: cannot execute: No such file or directory
```

I removed grumphp like explained here: https://github.com/phpro/grumphp/issues/26 , using `composer remove phpro/grumphp`. However I did not get the message `GrumPHP stopped sniffing your commits! Too bad ...`.

What can I do so I can commit again?

I'm guessing I can delete the `.git/hooks/pre-commit` file, but I'd like to be sure 😄 

Thanks

**Comment by veewee** [comment]
Hello @nWidart,

I've tries this myself with the latest version and it works like expected.
Can you give me some steps on how to reproduce the issue?

You can manually remove the hooks from the `.git/hooks` directory (pre-commit and commit-msg)

**Comment by nWidart** [comment]
Hmm strange. There aren't many ways to remove a package, since I used composer remove.

This was the output:

```
 ~/Sites/Asguard/Extra-Modules/blog-block-app-20/Modules/Blog ⮀ 2.0●● ⮀ 9m ⮀ composer remove phpro/grumphp                                                                ⮂  
phpro/grumphp could not be found in require but it is present in require-dev
Do you want to remove it from require-dev [yes]? yes
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 0 installs, 8 updates, 19 removals
  - Removing symfony/dependency-injection (v3.3.2)
  - Removing psr/container (1.0.0)
  - Removing symfony/config (v3.3.2)
GrumPHP can not sniff your commits. Did you specify the correct git-dir?

  - Removing phpro/grumphp (v0.9.6)
  - Removing composer/composer (1.4.2)
  - Removing composer/ca-bundle (1.0.7)
  - Removing composer/semver (1.4.2)
  - Removing composer/spdx-licenses (1.1.6)
  - Removing justinrainbow/json-schema (5.2.1)
  - Removing seld/cli-prompt (1.0.3)
  - Removing seld/phar-utils (1.0.1)
  - Removing gitonomy/gitlib (v1.0.2)
  - Removing seld/jsonlint (1.6.0)
  - Removing symfony/options-resolver (v3.3.2)
  - Removing symfony/proxy-manager-bridge (v3.3.2)
  - Removing ocramius/proxy-manager (2.0.4)
  - Removing zendframework/zend-code (3.1.0)
  - Removing zendframework/zend-eventmanager (3.1.0)
  - Removing ocramius/package-versions (1.1.2)
  - Updating symfony/yaml (v3.3.2 => v3.3.5) Loading from cache
  - Updating monolog/monolog (1.22.1 => 1.23.0) Loading from cache
  - Updating symfony/debug (v3.3.2 => v3.3.5) Loading from cache
  - Updating symfony/console (v3.3.2 => v3.3.5) Loading from cache
  - Updating symfony/finder (v3.3.2 => v3.3.5) Loading from cache
  - Updating symfony/process (v3.3.2 => v3.3.5) Loading from cache
  - Updating symfony/event-dispatcher (v3.3.2 => v3.3.5) Loading from cache
  - Updating symfony/filesystem (v3.3.2 => v3.3.5) Loading from cache
Writing lock file
Generating autoload files

```

**Comment by veewee** [comment]
Can you run `./vendor/bin/grumphp git:deinit -vvv` manually and show me that output?
As you can see, this command is failing in your installation.

**Comment by nWidart** [comment]
well there is no grumphp binary anymore since the grumphp package was removed, hence the error. To me it looks like the removal process just didn't remove the 2 hooks you pointed out.

**Comment by veewee** [comment]
During the deinstallation there is as you can see in the logs:

```
GrumPHP can not sniff your commits. Did you specify the correct git-dir?

  - Removing phpro/grumphp (v0.9.6)
```

So it first runs the hook and next removes grumphp.
Can you reinstall Grumphp and try to run that command to see why it is failing?

**Comment by nWidart** [comment]
I've re-added grumphp and ran your command. This is the output:

```
GrumPHP stopped sniffing your commits! Too bad ...
```

Does this mean that this should be called manually before removing the package?

Thanks,

**Comment by veewee** [comment]
No, that is the command that is being executed during the removal of the package.
It seems to work now. Just as in #26 the problem disappeared

**Comment by nWidart** [comment]
Well it worked because I called it manually. not because it did it automatically on `composer remove`. Also it re-installed a newer version, I was on 0.9 before.

**Comment by nWidart** [comment]
I just tested again with `v0.11.6`, it did remove the hooks on composer remove.

I then installed version 0.9 specifically, removed it, and this time it did remove the hooks... So I'm confused as to why it didn't the first time around.

Anyway, it's strange but works, I guess.

Thanks for your help! 😄

**Comment by veewee** [comment]
Indeed strange. Thanks for the fast feedback! Feel free to log an additional issue if you have more information.

**Comment by anotherjames** [comment]
For anyone that runs into this too; I found the reason my grumphp did not cleanly install was that the `composer remove` command automatically removed the grumphp plugin from the list of allowed plugins - so although the git hook was successfully removed on that particular run, when I or colleagues later checked out that branch and ran `composer install` to bring in the change to remove grumphp, the plugin was no longer in the list of allowed extensions, so it couldn't run to remove the hook. A solution is to manually ensure the grumphp plugin is kept in the `allow-plugins` list in composer.json. Maybe the plugin should also emit a warning to suggest developers should do that after they remove the plugin?
