### ISSUE TITLE
git:init improvements

### ISSUE THREAD

**Issue by oojacoboo** [phpro/grumphp#387]
I'm trying to setup an internal composer package that we include in all repos.  Our repos have varying structures and `.git` is not always located at the same location.

I'm proposing 2 options with the second one preferred.

1.  For `git_dir` parameter, support the null, `~` option and use a more intelligent git root lookup using, `git rev-parse --show-toplevel`.  This would be nice for people.  It would, in fact, not work for us since we run composer commands on a Docker container in order to ensure all dependency requirements are met.  Our docker containers do not mount the entire git repo, but only the source code that's necessary for php.  Therefore, it would never be able to find the true git root.
2.  Add a parameter option to disable git:init (need this)

As it is now, a `.git` directory is being initialized in our src code, but not at the repo root.  This is causing issues and I cannot find any other way to address this issue.  I may have to add a `post-install-cmd` and `post-update-cmd` script to `git:deinit`, then require all installations of this package to manually run a custom init script that wraps `git:init`.

Any other advice is much appreciated.  Thanks!

**Comment by veewee** [comment]
@oojacoboo,

That seems like a rather complex setup which we probably won't support since we do need the .git directory.

You can always skip code execution during installation with the `--no-plugins` flag:

```sh
composer require phpro/grumphp --no-plugins
```

I hope this fixes your issue?

**Comment by oojacoboo** [comment]
Thanks @veewee.  Does a subsequent update not trigger checks on the "plugins"?  I'm assuming not.

I've hacked my way around all of this with a custom repo for our coding standards that implements grumphp and other deps.  It's probably one of the nastier hacks I've done recently.  Most of the issue is surrounded by strict path requirements without options to set these dynamically.

Sidebar: I think the PHP/composer community needs to step away from the assumption that repositories will be built with only PHP code and consequently have only PHP dependencies.
