### ISSUE TITLE
Auto git add on next run of grumphp

### ISSUE THREAD

**Issue by Mte90** [phpro/grumphp#396]
| Q               | A
| --------------- | ---
| Version         | `grumphp -V`
| Bug?            | no
| New feature?    | yes
| Question?       | yes
| Documentation?  | no
| Related tickets | #100, #123, #365

# workflow

- Edit your code
- git add and git commit
- grumphp is executed
- grumphp report few errors and the commit is not finalized
- edit your code to fix it
- new execution of git commit
- grumphp say that is ok because the file are fixed but the changes are not committed

I think that will be useful that on git commit git add will run again with the same files of before to avoid this problem and next grumphp is executed.

**Comment by veewee** [comment]
This is not something we can easily solve since the external tools run on the current state of the filesystem.

You could set the ignore_unstaged_changes to true, but that parameter should be considered risky.
Additional info: https://github.com/phpro/grumphp/blob/master/doc/parameters.md

Additional info:

- #100
- #123
- #365

**Comment by Mte90** [comment]
Why is not possible to do a `git add` with the list of files? GrumPHP already get a list of files of this commit so execute it before the grumphp doesn't be so much difficult to implement.
The tools run of course with filesystem so this behaviour should be the right one because we want to commit the files in the actual status.
Maybe add an alert that the files are changed and not committed can be another solution.
Actually grumphp is pretty annoying for this behaviour of re-add manually the files instead do it automatically, maybe with a flag this behaviour can be fixed.

**Comment by veewee** [comment]
GrumPHP will never make descisions on what to add to git - we want you to have full control about your code. This means that adding the files to git is the developers responsibility.
Displaying a warning when there are still unstaged changes is possible by adding an event listener but it is just a non-blocking message which doesn't really add any value.

**Comment by Mte90** [comment]
Good point, so if I want to add in any case that feature?
I can use https://github.com/phpro/grumphp/blob/master/doc/tasks/shell.md?
This is executed before the others? I can do it a bash script that add the new code on git so I will avoid this behaviour issues.

**Comment by veewee** [comment]
Thats a possibility. You'll have to give the shell task a high priority as described in https://github.com/phpro/grumphp/blob/master/doc/tasks.md#metadata

**Comment by Mte90** [comment]
I discovered the command (https://stacktoheap.com/blog/2016/01/02/git-add-only-files-already-staged/):
```git update-index --again``` 
This do the magic that auto add the file in staging before the commit, now I am working to adding as a shell script.

**Comment by Mte90** [comment]
```
shell:
            metadata:
                priority: 10
            scripts: 
                - ["'git update-index --again'"]
            triggered_by: ['php','json','yml']
```
Seems doesn't work because the shell is expecting a shell script to parse and not a unix command

**Comment by Mte90** [comment]
Ok I created a bash script with this command in /usr/local/bin and added the absolute path to the script in grumphp and I resolved :-D

I nice Grumphp trick, maybe is perfect to the wiki because I was not the first one asking for this feature

**Comment by Mte90** [comment]
I was thinking (the usual idea that become when you are doing something boring) the grumphp has the `-n` flag to execute the commit without grumphp, an idea can another command that execute the command that I mentioned and will be git to do the magic with avoiding of many issue and less code.
