### ISSUE TITLE
Install/uninstall dependencies on-demand independently from the project

### ISSUE THREAD

**Issue by 1ed** [phpro/grumphp#412]
| Q               | A
| --------------- | ---
| Version         | -
| Bug?            | no
| New feature?    | yes
| Question?       | no
| Documentation?  | no
| Related tickets | -

That would be very cool, if grumphp could handle its tasks dependencies independently from project dependencies. Something like Symfony did with the phpunit-bridge and simple-phpunit https://github.com/symfony/symfony/blob/b6e9471ded49e698c8c2468be9c1b42c621efeac/src/Symfony/Bridge/PhpUnit/bin/simple-phpunit.

**Comment by veewee** [comment]
Hi @1ed,

Thanks for the suggestion.  I'd accept a PR for that.

**Comment by Snaver** [comment]
It may use the same method, but I saw this Composer plugin the other day which I thought was really cool, May solve this issue too?

https://github.com/bamarni/composer-bin-plugin

**Comment by veewee** [comment]
Closing this one since composer-bin-plugin is the way to go for this.
