### ISSUE TITLE
How to choose php version?

### ISSUE THREAD

**Issue by indapublic** [phpro/grumphp#425]
| Q               | A
| --------------- | ---
| Version         | `0.12.0`
| Bug?            | no
| New feature?    | no
| Question?       | yes
| Documentation?  | no
| Related tickets | comma-separated list of related tickets

I'm using OSX with PHP 7.1 (installed via brew) and Symfony project. I received this errors while commit:

> Warning: Unsupported declare 'strict_types' in /Volumes/Data/www/com.indapublic/billing/api/vendor/ocramius/proxy-manager/src/ProxyManager/Configuration.php on line 19
> 
> Parse error: parse error, expecting `';'' or `'{'' in /Volumes/Data/www/com.indapublic/billing/api/vendor/ocramius/proxy-manager/src/ProxyManager/Configuration.php on line 87

Nginx using PHP7.1, PHP CLI is 7.1 too.

How I can to fix it? Thank you

**Comment by veewee** [comment]
Hi @indapublic,

You need to specify a version of proxy-manager that works for your PHP version (7.1). You probably want one of the 2.1 range.

**Comment by indapublic** [comment]
@veewee Thanks for reply. I have correct version.

> "ocramius/proxy-manager": "^2.1"

And we can see it on this warning: 

> Unsupported declare 'strict_types' in 

But seems like checks running using not php 7.1.

> php-fpm -v
> PHP 7.1.11 (fpm-fcgi) (built: Oct 27 2017 11:00:47)

> php -v
> PHP 7.1.11 (cli) (built: Oct 27 2017 11:00:43) ( NTS )

**Comment by keradus** [comment]
no way to reproduce was provided, no reference to repo, how grumphp was installed

google to the rescue:
https://github.com/Ocramius/ProxyManager/issues/328#issuecomment-304170899 (and previous messages to know how to track the issue)

you are executing grumphp under php5. that's the issue.

**Comment by indapublic** [comment]
As you can read, I'm using Symfony project so grumphp installed via composer.
I know it's environment issue. So you not need my repo.
> you are executing grumphp under php5. that's the issue.
I know about it. Because topic name is "How to choose php version".
But, as you can see, my main php is 7.1 (using in nginx and cli version).
So your answer is not useful.

**Comment by keradus** [comment]
> As you can read, I'm using Symfony project so grumphp installed via composer.

huh? fact you are using some Sf project doesn't inticate the way of installing the tools like grumphp or others.


> I know it's environment issue.
> my main php is 7.1 (using in nginx and cli version).
> So your answer is not useful.

yet, you refuse to share any details allowing to reproduce your local environment that is causing issues to you ;) without details, it's unlikely you will get help.

**Comment by indapublic** [comment]
> `which php` --version
> PHP 7.1.11 (cli) (built: Oct 27 2017 11:00:43) ( NTS )
> Copyright (c) 1997-2017 The PHP Group
> Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
>     with Zend OPcache v7.1.11, Copyright (c) 1999-2017, by Zend Technologies

**Comment by indapublic** [comment]
Ok. Removed grumphp from project. Thanks for any help.

**Comment by veewee** [comment]
Hi @indapublic, 

Sad to hear that your local configuration caused an uninstall of GrumPHP.
If it's any help: I've seen this issue before.

You are probably using a git UI like sourcetree, which doesn't import your local $PATH variable before running the scripts. This causes a lot of issues like a different PHP version than the one installed locally or exectuables that can't be found.

You can fix this by adding following line to the git hooks:

```sh
export PATH=/usr/local/bin:$PATH
```

Related resources:
- https://community.atlassian.com/t5/Bitbucket-questions/SourceTree-Hook-failing-because-paths-don-t-seem-to-be-set/qaq-p/274792

Feel free to try this out and give us additional feedback on this issue.

**Comment by Landerstraeten** [comment]
Hi @indapiblic,

I also think you are using a GUI like sourcetree. Am I correct? If not, we still can try something else to let grumphp work for you.

**Comment by indapublic** [comment]
@veewee @Landerstraeten You are my heroes! Seems that this is exactly what I need. Thank you very much.

**Comment by veewee** [comment]
No problem. I'm reopening the issue so that we don't forget to add this to the das page.

**Comment by redgluten** [comment]
> Hi @indapublic,
> 
> Sad to hear that your local configuration caused an uninstall of GrumPHP.
> If it's any help: I've seen this issue before.
> 
> You are probably using a git UI like sourcetree, which doesn't import your local $PATH variable before running the scripts. This causes a lot of issues like a different PHP version than the one installed locally or exectuables that can't be found.
> 
> You can fix this by adding following line to the top of the git hooks:
> 
> ```shell
> export PATH=/usr/local/bin:$PATH
> ```
> 
> Related resources:
> 
> * https://community.atlassian.com/t5/Bitbucket-questions/SourceTree-Hook-failing-because-paths-don-t-seem-to-be-set/qaq-p/274792
> 
> Feel free to try this out and give us additional feedback on this issue.

Just a little help for those having this issue on an M1 Mac and installed PHP via the latest Homebrew version: you want to the `$PATH` line to be like this:

```shell
export PATH=/opt/homebrew/bin/:$PATH
```
