### ISSUE TITLE
Gradually upgrade to PHP 7.0

### ISSUE THREAD

**Issue by veewee** [phpro/grumphp#482]
Follow up issue of #434.

These steps should be done in separate - easy to review - PRs.

- [ ] Inject strict parameters in functions
- [ ] Inject strict return types in functions
- [ ] Remove unnecesary docblocks
- [ ] Declare strict types
- [ ] Upgrade configuration

**Comment by Landerstraeten** [comment]
7.0 or 7.1 ?

**Comment by veewee** [comment]
Lets start with adopting the new 7.0 options.  ;)

**Comment by veewee** [comment]
@Landerstraeten Any updates on this? Does the grumpy-seventies branch works for you?

**Comment by richardhughes** [comment]
Hey @veewee, How is this progressing? If you need a hand, I'll be happy to help
