### ISSUE TITLE
Add new vimeo/psalm task

### ISSUE THREAD

**Issue by regniblod** [phpro/grumphp#495]
| Q               | A
| --------------- | ---
| Version         | `0.14.0`
| Bug?            | no
| New feature?    | yes
| Question?       | yes
| Documentation?  | no
| Related tickets | -

It would be cool to add a task to run [Psalm](https://github.com/vimeo/psalm), which according to their Github repo is 
> A static analysis tool for finding errors in PHP application

similar to PHPStan, which already is a task, so I think it makes sense to add this one too.

If the request is accepted I can work on the feature and open a PR.

**Comment by veewee** [comment]
Hi @regniblod,

Thanks for logging the issue. 
It looks like a great addition to this project. Feel free to open a PR.

**Comment by janvernieuwe** [comment]
I know this extension is out there: https://github.com/weemen/GrumPHPPsalm
Have not tried it myself but the maintainer is also open for PR's in case you need something as far as i know.

**Comment by regniblod** [comment]
Hey @janvernieuwe thanks for the link! I didn't know there was already an extension for PSALM.

BTW how it's decided if a new task should be an extension or added to GrumPHP core? I guess if it's something specific for my project or for a small number of projects it should be an extension, but what about things like PSALM, that everyone could take advantage of using?

**Comment by janvernieuwe** [comment]
We didn't decide this, weemen just created the extension.
We would ofcourse be glad to merge a PR to add this functionality to the core of GrumPHP itself!

**Comment by muglug** [comment]
Just saw this, happy to help out (I made Psalm)

**Comment by Landerstraeten** [comment]
Done
