### ISSUE TITLE
question: how to run non-shell command?

### ISSUE THREAD

**Issue by keradus** [phpro/grumphp#500]
hi !
I am aware that there is a `shell` task, but let say that I want to simply run
`php execute-sth.php`
or
`composer diagnose`
or even better:
`./my-magic-file`

I can't get shell task to do it, as it's prepending command with `sh`, and it wont work, for example:
```
ker@dus:~/tmp λ sh composer diagnose
sh: 0: Can't open composer

```

can you suggest solution ? thanks !

**Comment by keradus** [comment]
Ah, as non-shell guy, I wasn't aware of that param,
maybe it would be nice to add it to docs? (I was there before raising a question, but simply `-c` wasn't there ;) )

**Comment by Mavlyan** [comment]
@keradus Sure! I've made pull request #502 
Waiting for review and reposne

**Comment by keradus** [comment]
love that ;)
