### ISSUE TITLE
how to configure meqp2 tool

### ISSUE THREAD

**Issue by sivajik34** [phpro/grumphp#505]
| Q               | A
| --------------- | ---
| Version         | `0.14.0`
| Bug?            | no
| New feature?    | yes
| Question?       | yes
| Documentation?  | yes/no
| Related tickets | comma-separated list of related tickets

how to configure following tool
https://github.com/magento/marketplace-eqp

**Comment by sivajik34** [comment]
I found following the documentation. but show_warnings not working.
Magento
If you want to use Phpcs for your Magento projects, you can require the magento-ecg repo.

composer require --dev magento-ecg/coding-standard
Following this, you can add the path to your phpcs task.

# grumphp.yml
parameters:
    tasks:
        phpcs:
            standard: "vendor/magento-ecg/coding-standard/Ecg/"
            show_warnings: false

**Comment by jyggen** [comment]
`show_warnings` was removed in GrumPHP 0.14.0, use `warning_severity` instead.

**Comment by sivajik34** [comment]
thank you.
