### ISSUE TITLE
PHP Fatal error:  Cannot redeclare composerRequire

### ISSUE THREAD

**Issue by natenolting** [phpro/grumphp#51]
So I thought I'd  give this a go after it was talked about at the the last Nomad Php Webinar I attended. I'm trying this on an empty project, the only code in my root that's not in my .gitignore is a readme.md, composer.json and grumphp.yml. On commit I get this error. 

```
git commit
PHP Fatal error:  Cannot redeclare composerRequire6fe528f671e512f2b4fb01800c0ca522() (previously declared in /Users/xxx/yyy/zzz/vendor/composer/autoload_real.php:52) in /Users/xxx/yyy/zzz/vendor/composer/autoload_real.php on line 55

Fatal error: Cannot redeclare composerRequire6fe528f671e512f2b4fb01800c0ca522() (previously declared in /Users/xxx/yyy/zzz/vendor/composer/autoload_real.php:52) in /Users/xxx/yyy/zzz/vendor/composer/autoload_real.php on line 55
```

**Comment by veewee** [comment]
Hi @natenolting,

Thanks for trying GrumPHP and reporting this issue!

It might be possible that the composer autoload file was included twice.
I fixed this in this commit: https://github.com/phpro/grumphp/commit/8c7a0cd0266e023d9f5e1f6bdc5d5882f7552e48 .
This fix is available at version [0.5.1](https://github.com/phpro/grumphp/releases/tag/v0.5.1).

Can you verify if this fixes your problem?
If this solution doesn't fix your problem, can you try running following command?

```
git diff -r -p -m -M --full-index --staged
```

My best guess is that the `vendor` folder is included in this diff. 

Just out of curiosity: can you tell me which webinar you attended?

**Comment by natenolting** [comment]
Looks like that did the trick, thanks!

**Comment by matthisstenius** [comment]
Can confirm that i get this exact error on version 0.5.2. Sometimes a composer update does the trick but other times i have to do a complete uninstall and then install it again.
