### ISSUE TITLE
phpstan task should run on all configured files, all the time

### ISSUE THREAD

**Issue by jaydiablo** [phpro/grumphp#512]
| Q               | A
| --------------- | ---
| Version         | 0.14.1
| Bug?            | yes
| New feature?    | no
| Question?       | no
| Documentation?  | no
| Related tickets | 

Currently, grumphp builds a file list for the phpstan task, which may only be the changed files (in the case of the git pre-commit hook), but this can result in missed errors, as it's possible that the changed files may have changes in them that affect other files that aren't being analyzed (see some more discussion about this here: https://github.com/phpstan/phpstan/issues/934#issuecomment-383002766).

>See, you cannot run analysis only on the changed files. If you change A.php, it's not sufficient to analyse only A.php, because by changing it, you could have broken a different file that hasn't changed, but it's dependent on some detail from A.php, like method arguments.

The task should **always** run on **all** configured files regardless of the context to avoid missing such errors (at least until the "changed-files" feature that is mentioned in that linked phpstan ticket lands).

Thanks!

**Comment by SerkanYildiz** [comment]
You can run ```grumphp run``` to check all files. Maybe it is possible to add a shell task to run this?

**Comment by veewee** [comment]
Made it configurable in #807.
Thanks for pointing it out!
