### ISSUE TITLE
Ability to run the checks only on diifs

### ISSUE THREAD

**Issue by luemic** [phpro/grumphp#514]
| Q               | A
| --------------- | ---
| Version         | any
| Bug?            | no
| New feature?    | yes
| Question?       | yes
| Documentation?  |no
| Related tickets | 

Hi there,

is there an hability to run the checks only on changed lines? Or if this is not possible a way to find out if there would (quality) regressions in a commit (runs checks without changes and with changes ans compare results)?

 Kind regards

Michael

**Comment by Landerstraeten** [comment]
Hi Michael.

It's possible to run grumphp on changed files only. As described on https://github.com/phpro/grumphp/blob/master/doc/commands.md#git-hooks you can run `$ grumphp git:pre-commit`
