### ISSUE TITLE
Add external URL for config-default-path

### ISSUE THREAD

**Issue by mgeoffray** [phpro/grumphp#521]
| Q               | A
| --------------- | ---
| Version         | `*`
| Bug?            | no
| New feature?    | yes
| Question?       | yes
| Documentation?  | no
| Related tickets | none

We have several projects using the same `grumphp.yml` file and it will be useful that this file can be externalized.    
Maybe something like that:    
```json
"extra": {
  "grumphp": {
    "config-default-path": "https://raw.githubusercontent.com/phpro/grumphp/master/grumphp.yml"
  }
},
```   

Unless I am mistaken it is not possible at the moment.    
Is it planned to be able to add an external URL for the GrumPHP extra config `config-default-path`?    
Is there a possible workaround?   
   
Thank you!

**Comment by mattheo-geoffray** [comment]
Hi @veewee ,
perfect, using a third composer library may made the trick for us. 
  
thank you for your very quick answer!

**Comment by veewee** [comment]
No problem! :)

**Comment by mgeoffray** [comment]
Hi @veewee ,
perfect, using a third composer library may made the trick for us.

thank you for your very quick answer!   
I am closing that issue
