### ISSUE TITLE
Better blacklist (function) detection

### ISSUE THREAD

**Issue by nilportugues** [phpro/grumphp#53]
Hello! 

You should change your implementation for detecting functions. 

You may want to take a look at how I've done it in my package: https://github.com/nilportugues/php_forbidden_functions  and bring it to your code or use it. Up to you :)

But blacklisting  `die(` will detect when `die()` but also `->die()`

**Comment by veewee** [comment]
Hello @nilopc,

Thanks for mentioning!

You are absolutely correct: the blacklist task should be smarter.
Your package looks great but it can only be used for forbidden functions in PHP context.
The blacklist task should also work on other files then PHP and on other things then functions. For example: you want to check docblocks, comments, ...

**Comment by nilopc** [comment]
Got you covered for PHP Docblocks and Comments in files https://github.com/nilportugues/php_todo_finder ... just change the listed expressions for whatever.

For other than PHP... well, you will have to tokenize the files in order to effectively detect docblocks, comments and unwanted expressions etc etc.

For CSS: https://github.com/symfony/css-selector could be helpful.
For JS: https://github.com/kbjr/UglifyJS.php/blob/master/javascript-tokenizer.php

**Comment by llaville** [comment]
@veewee  as asked in https://github.com/phpro/grumphp/issues/101#issuecomment-179659390, why not named my new task "php_forbidden". This will avoid confusion with default Parser implemented (PHP_Parser).
Before to push my code I want to test more conditions and why not see how it could handle a new parser.

**Comment by veewee** [comment]
or maybe just `php_blacklist` to use the same term for the tasks that check for forbidden stuff?
What do you mean with 'how it could handle a new parser'?

**Comment by llaville** [comment]
:+1: for name `php_backlist`

> What do you mean with 'how it could handle a new parser'?

I've implemented a solution based like linter to allow to use PHP_Parser but any other one we may add after

**Comment by kgust** [comment]
:+1: for @nilportugues comment about tokenizing javascript and using css selectors. The Javascript task could be very similar to the php_blacklist.

I'm not sure how the CSS task would work.

**Comment by llaville** [comment]
@veewee  I've just pushed code for review !
