### ISSUE TITLE
Allow array of failed / succeeded ascii art; choose one randomly

### ISSUE THREAD

**Issue by q0rban** [phpro/grumphp#530]
| Q               | A
| --------------- | ---
| Version         | `0.11.6`
| Bug?            | no
| New feature?    | yes
| Question?       | no
| Documentation?  | no
| Related tickets | comma-separated list of related tickets

It'd be fun to have an array of different ascii txt files, and have GrumPHP choose one randomly. For example, I'd like to have a random Mister Rogers quote:

```
parameters:
  ascii:
    failed: 
      - what-do-you-do-with-the-mad-that-you-feel.txt
      - anything-mentionable-is-manageable.txt
      - go-ahead-and-cry-im-here-to-be-with-you.txt
    succeeded:
     - you-are-special.txt
     - you-are-my-friend.txt
     - its-a-beautiful-day-in-the-neighborhood.txt
```

**Comment by veewee** [comment]
Hi @q0rban 

It is simple to add, I'd accept a PR that adds this. Be sure to add tests and updated docs.

**Comment by q0rban** [comment]
@veewee PR in #538! 😀
