### ISSUE TITLE
grumphp v0.14.2 release date

### ISSUE THREAD

**Issue by DidYoun** [phpro/grumphp#535]
| Q               | A
| --------------- | ---
| Version         | `grumphp -V`
| Bug?            | no
| New feature?    | yes
| Question?       | yes
| Documentation?  | no
| Related tickets | [527](https://github.com/phpro/grumphp/issues/527)

Hi,

I'd like to know when the new tag (0.14.2) would be released pls ? I'd like to implement the new feature from the related ticket up.

Thanks,

**Comment by veewee** [comment]
Hi @DidYoun,

We released that version today: https://github.com/phpro/grumphp/releases/tag/v0.14.2
