### ISSUE TITLE
Relative paths on Windows Git Bash

### ISSUE THREAD

**Issue by lasselehtinen** [phpro/grumphp#55]
Seems like there is some kind of problem with the relative paths in Git Bash and MINGW32 on Windows environments. It works if I place the absolute path to grumphp.yml, but I would rather not use that since it will break soon as somebody clones the repo to somewhere else. I tried various different options like "./" without help. I am using dev-master at the moment.

```
lasleh@CPB2265 /C
$ mkdir test

lasleh@CPB2265 /C
$ cd test

lasleh@CPB2265 /C/test
$ git init
Initialized empty Git repository in c:/test/.git/

lasleh@CPB2265 /C/test (master)
$ grumphp git:init

  [Symfony\Component\Filesystem\Exception\IOException]
  Failed to create "../../C:/test/.git/hooks/": mkdir(): Invalid argument.
```

**Comment by veewee** [comment]
I haven't used Git Bash on windows yet. Will try to install it in the weekend.
Is it possible that the C folder symlinks to C: ?
Do you get the same results when you run following commands:

{code}
$ cd /C:
$ mkdir test
$ cd test
$ git init
$ grumphp git:init
{code}

**Comment by lasselehtinen** [comment]
Unfortunately that does not work, because Git Bash maps each Windows drive Letter /letter. So for example C:\test becomes /c/Test. 

```
lasleh@CPB2265 /c/test (master)
$ php -r "var_dump(getcwd());"
string(7) "c:\test"
```
And both of these work:

```
cd /c/test
cd c:\test
```

So I assume there is something funny going on when you try to determine the absolute path when a relative one is given.

**Comment by veewee** [comment]
Hi @lasselehtinen ,

I tested git bash and it seems to work here:

```
# I started gi bash with: sh.exe --login
$ cd /C
$ mkdir test
$ cd test
$ git init
$ grumphp configure
$ grumphp git:init
```

The result I retrieve is:
```
$ cat .git/hooks/pre-commit
#!/bin/sh
# ...
(cd "./" && exec "c:\Users\Verweto-Win\AppData\Roaming\Composer\vendor\bin/grump
hp" "git:pre-commit" "--config=grumphp.yml" '--skip-success-output')

# ....
```
So this is working. Maybe you can try upgrading git bash?

**Comment by lasselehtinen** [comment]
That seemed to be the case. I was using old 1.9.3 version of Git Bash whereas updating to 2.6.3 made the problem go away.
