### ISSUE TITLE
FR: Ability to give shell task a label

### ISSUE THREAD

**Issue by Jamesking56** [phpro/grumphp#579]
| Q               | A
| --------------- | ---
| Version         | `0.14.3`
| Bug?            | no
| New feature?    | yes
| Question?       | no
| Documentation?  | no
| Related tickets | #566

It would be great if we could add a label to the `shell` task so that we can rename it when doing `grumphp run`.

For example, say I had a specific tool that was not a task in grumphp. Instead of it showing `Running task x/x: Shell...` in the output. It would be great if it could be re-labelled, for example `Running task x/x: MyAwesomeTool....`.

**Comment by veewee** [comment]
Hello @Jamesking56,

Can you give me an extended example on what you are trying to achieve?
I don't fully understand your question.

**Comment by Jamesking56** [comment]
I'm running a custom tool thats not open source by using the `Shell` task in GrumPHP. In the output I get:

`Running task x/x: Shell...`

It would be great if I could set the label, so that the output was:

`Running task x/x: MyTool...`

**Comment by veewee** [comment]
Fixed in #711
