### ISSUE TITLE
Provide option to run a single/list of tasks from the config

### ISSUE THREAD

**Issue by paslandau** [phpro/grumphp#580]
| Q               | A
| --------------- | ---
| Version         | `0.14.3`
| Bug?            | no
| New feature?    | yes
| Question?       | yes
| Documentation?  | probably
| Related tickets | 

It would be great to have an option in the `run` command to specify a list of tasks that should be run by grumphp instead of running all tasks

Proposal
==
Consider the following grumphp.yml

```yml
parameters:
  tasks:
    composer: []
    composer_require_checker:
      ignore_parse_errors: true
    file_size:
      max_size: 1M
```

Run grumphp via

 `vendor/bin/grumphp run --tasks=composer,file_size`

The `--tasks` option would be split on "," and the resulting values would act as a "whitelist" for the given config. I.e. only `composer` and `file_size` would run:

```
Running task  1/2: Composer... ✔
Running task  2/2: FileSize... ✔
```

`composer_require_checker` would be omitted since it is not listed in the option.

If `--tasks` is empty / not given, the default is the current behavior (maintaining bc).

Use cases
===
- Being able to easily re-run a specific task
  - On "long" task chains this helps in verifying the reported issue is fixed without the need of running every other (probably unrelated) check as well
- Quickly explore "new" tasks. 
  - Currently, I need to duplicate my grumphp.yml, remove all tasks and keep only the required ones. This is really inconvenient, especially when setting up grumphp initially
- Sometimes, I only need to run a specific taks / combination of tasks (e.g. parallel-lint and phpstan in order to quickly verify that there are no syntactical errors that will interrupt a subsequent unit/integration/end2end test run [which usually takes much longer])
- Keep only one config file for different scenarios. 
  - We use grumphp not only for commit hooks but also for general code checks on the "full" codebase, e.g. before we create a pull request for code review. Those include an extented set of tasks (e.g. composer-require-checker) that needs to only run before an actual push to remote but not on every commit. Currently, we need to maintain separate files to archieve this. With the `--tasks` option we could keep one file and pick the subset of tools that we need. 

Implementation
===
I was having a quick look into the run command and this should be achievable with minimal effort, i.e.
- add `tasks` option to `RunCommand` & parse comma separated string
- add `tasks` property to `TaskRunnerContext`
- in `TaskRunner::run()` filter `TaskCollection` based on the task name, i.e.
```php
        $tasks = $this->tasks
            ->filterByContext($runnerContext->getTaskContext())
            ->filterByTestSuite($runnerContext->getTestSuite())
            ->filterByTaskName($runnerContext->getTasks())
            ->sortByPriority($this->grumPHP)
        ;
```
- with `TaskCollection::filterByTaskName()` as 
```php
    /**
     * @param string[]|null $tasks
     *
     * @return TasksCollection
     */
    public function filterByTaskName($tasks)
    {
        return $this->filter(function (TaskInterface $task) use ($tasks) {
            if (empty($tasks)) {
                return true;
            }
            return in_array($task->getName(), $tasks);
        });
    }
```

I would prepare a PR if you'd like to move forward.

Cheers
Pascal

**Comment by veewee** [comment]
Hi @paslandau,

Looks like a great addition. I'dd accept a PR for that.
Note that the last 2 use cases can be covered by specifying testsuites (see https://github.com/phpro/grumphp/blob/master/doc/testsuites.md)

**Comment by paslandau** [comment]
> Note that the last 2 use cases can be covered by specifying testsuites (see https://github.com/phpro/grumphp/blob/master/doc/testsuites.md)

Ha. Totally missed that.. the PR anyway :)
