### ISSUE TITLE
Add passthru option to config to pass arbitrary options to tasks

### ISSUE THREAD

**Issue by paslandau** [phpro/grumphp#583]
| Q               | A
| --------------- | ---
| Version         | `0.14.3`
| Bug?            | no
| New feature?    | yes
| Question?       | yes
| Documentation?  | probably
| Related tickets | 

Having a "mapping" layer from `grumphp.yml` to the specific options for each tasks makes sense, because it makes the package more resilient to changes of the underlying libraries and enables a more consistent config for the grumphp user.

However, since most of the supported tools are under active devlopment, grumphp users can't make use of newly provided options that are not yet implemented. I have two concrete examples of unsupported options (though not really new):
- `phpcs` and the `--parallel` option (see https://github.com/squizlabs/PHP_CodeSniffer/blob/390bffe2265aac8184fdf86400c0d0841e65bc4b/src/Config.php#L53 )
- `phpmnd` and the `ignore-funcs` option (see https://github.com/povils/phpmnd/blob/acf9a485673d6240110ea252ca3ff201b59e14f0/src/Console/Command.php#L55 )

I resorted to 
- duplicate the existing task
- add it as a service in `grumphp.yml`
- replace the original task with the newly created one

This is actually quite a lot of work, just to get a parameter passed to the underlying task.

Proposal
==
Consider the following grumphp.yml

```yml
parameters:
  tasks:
    phpcs: 
      passthru: "--no-cache --parallel=4"
    phpmnd: 
      passthru: "--ignore-funcs=4"
```

While parsing and providing the arguments to the underlying tool, each task would simply append the value of `passthru` to the command. Of course this should not keep contributors from adding a "stable" way to provide the missing option via `grumphp.yml`, but it provides a much more convenient way for the end user and thus increases adoptability.

Implementation
==
- Since this is a rather "global" option, it should probably be implemented in the base classes under `Task/Abstract*Task`. This would still require to "touch" a lot of Tasks, though...
- The "adding" could be implememted in `ProcessArgumentsCollection` as something like `::addRawOptionString`:
```php
    /**
     * @param string $rawOption
     */
    public function addRawOptionString($rawOption)
    {
        if (!$value) {
            return;
        }

        $this->add($rawOption);
    }
```

Thoughts?

Cheers
Pascal

**Comment by veewee** [comment]
We investigeted this in #716 
There is no easy or generic way to implement this:
The process builder is a separate layer inside this project. This means it doesn't really know about task metadata and there is no "generic" way to handle this without manually adding it to every task that triggers an external task. Therefor I am closing this issue. Still like the idea though, but doesnt seem feasible at this point.
