### ISSUE TITLE
FR: Add paratestphp/paratest task

### ISSUE THREAD

**Issue by paslandau** [phpro/grumphp#584]
| Q               | A
| --------------- | ---
| Version         | new release
| Bug?            | no
| New feature?    | yes
| Question?       | yes
| Documentation?  | yes
| Related tickets | 

- https://github.com/paratestphp/paratest
- run phpunit in parallel
- greatly improved performance
- would only implement this for the `grumpy_seventies` branch

Would create a PR if interested.

**Comment by Landerstraeten** [comment]
Done in #617 by @janvernieuwe
