### ISSUE TITLE
Add a new tasks "composer normalize" using package from localheinz/composer-normalize

### ISSUE THREAD

**Issue by drupol** [phpro/grumphp#595]
The goal of this issue is to track the development of a new Grumphp task that aim to provide a new "task" using the package [localheinz/composer-normalize](https://packagist.org/packages/localheinz/composer-normalize).

| Q               | A
| --------------- | ---
| Version         | `grumphp -V`
| Bug?            | no
| New feature?    | yes
| Question?       | no
| Documentation?  | no

Ping @localheinz

**Comment by veewee** [comment]
Will be handled in the PR
