### ISSUE TITLE
Support other PHP executable

### ISSUE THREAD

**Issue by rotemreiss** [phpro/grumphp#615]
| Q               | A
| --------------- | ---
| Version         | 0.14.3
| Bug?            | no
| New feature?    | yes
| Question?       | yes
| Documentation?  | yes
| Related tickets | Couldn't find related issues

First of all, it took me a while to find that great library, and that looks really great when compared to other ways to achieve similar functionality. So thanks :).

We are using [Lando](https://docs.devwithlando.io/) for our development environment and `grumphp` pre-commit fails (for a good reason) with:
```
# .git/hooks/pre-commit
/usr/bin/env: ‘php’: No such file or directory
```
The way we should run `grumphp` is `lando php ./bin/grumphp git:pre-commit` and that works great from the command line, but when trying to change `(cd "./" && printf "%s\n" "${DIFF}" | exec ./bin/grumphp 'git:pre-commit' '--skip-success-output')` (pre-commit file) to `(cd "./" && printf "%s\n" "${DIFF}" | lando php ./bin/grumphp 'git:pre-commit' '--skip-success-output')` - nothing happens (no errors, and no output).

Is that case supported somehow? I'll be happy to contribute that feature (in a generic way), but I need to make sure that this is not currently supported, and is that the right way to approach that issue?
The feature I'm imagining is to allow different php executables in grumphp.yml, something like `bin_file: 'lando php'` and that it will make the required change on the pre-commit file (without changing the grumphp file.
Another related question:
If I'm changing the pre-commit file like that:
```
# Run GrumPHP
# (cd "./" && printf "%s\n" "${DIFF}" | exec ./bin/grumphp 'git:pre-commit' '--skip-success-output')
lando php ./bin/grumphp 'git:pre-commit' '--skip-success-output'
```
It works great. Why do we need the diff printf? Is that really required to grumphp?

**Comment by veewee** [comment]
hello @rotemreiss,

Thanks for reporting!

That case is currently not available.
Since we recently introduced `git_hook_variables`, we might want to add an `EXEC_GRUMPHP_COMMAND` which has a default value of `exec`. You can then easily change it to whatever command you want to use. 

This would also be useful for running grumphp on multiple locally installed PHP versions.

More information on why the diff is added to the hook can be found here:
https://github.com/phpro/grumphp/issues/144
(It is related to `git commit -a` or `-p` not having the staged files yet at that point when running the diff in a separate process)

**Comment by rotemreiss** [comment]
@veewee Thanks for your quick and informative reply.
I'll be happy to contribute that feature, I'll try to work on it in a few days, but I'm wondering - #144 will probably be broken if not using exec since it will be opened on a new process (right?).

Do you have any idea why
```
(cd "./" && printf "%s\n" "${DIFF}" | lando php ./bin/grumphp 'git:pre-commit' '--skip-success-output')
```
Doesn't work?

**Comment by rotemreiss** [comment]
Ok.. So the problem with the above is that lando probably doesn't support piping data into it. I'll check that, but it will probably be an issue.. :confused:

**Comment by rotemreiss** [comment]
Linking to the Lando issue - https://github.com/lando/lando/issues/1558.
It seems like a bug in Lando and I assume that the feature we raised will work great with regular cases of other PHP executable names (e.g. `php55`, `php70`..).

I'll get back to it once I'll know if there's a solution on Lando's side.
