### ISSUE TITLE
Test for PHP piping support in git hooks

### ISSUE THREAD

**Issue by rotemreiss** [phpro/grumphp#619]
| Q               | A
| --------------- | ---
| Version         | 0.14.3
| Bug?            | no
| New feature?    | yes
| Question?       | yes
| Documentation?  | no
| Related tickets | #615, https://github.com/lando/lando/issues/1558, #144 

I'm having a problem that was described in the above tickets.
In short, [Lando](https://docs.devwithlando.io/) (Docker based development environment) seems to have a leak of support in piping data into its PHP containers and more than that - the execution fails silently instead of just not reading the input from STDIN or something.
I've opened a ticket on that issue, but I don't see it being resolved in the near future and I need a solution for using grumphp with our Lando based environments.

I've already contributed a feature to support other PHP executables that will allow us to replace the current `exec` command in the Git hooks with `lando php`, but it still won't work due to the mentioned bug.
The solution I want to implement is to test whether the current PHP executable supports piping data into it, and if it doesn't - just remove the piping. Something like that:
```
# Has piping support
(cd "${HOOK_EXEC_PATH}" && printf "%s\n" "${DIFF}" | $(EXEC_GRUMPHP_COMMAND) $(HOOK_COMMAND) "--git-user=$GIT_USER" "--git-email=$GIT_EMAIL" "$COMMIT_MSG_FILE")
```
with
```
# No piping support
$(EXEC_GRUMPHP_COMMAND) $(HOOK_COMMAND) "--git-user=$GIT_USER" "--git-email=$GIT_EMAIL" "$COMMIT_MSG_FILE")
```

I know that it will break #144 in case that piping isn't supported, but if piping isn't supported - it is already broken anyway! :)

If that sounds good till that part - that's already great.

Assuming that you folks accept my suggestion, I have 2 options for implementation:

1. Wrap the git hook itself with that check (e.g. in `.git/hooks/pre-commit`)
2. Generate the hooks with the right structure in the first place by adding that check on the `InitCommand` class (this solution is much better of course)

One more thing is the test itself. I thought about something like `echo "ok" | php -r 'while (false !== ($line = fgets(STDIN))) echo $line;'` and then check if the output equals to `ok`.

Can I go for it? Any thoughts or suggestions?

Thanks.

**Comment by veewee** [comment]
Hi @rotemreiss,

Since I am not familiar with lando, can you tell me how grumphp behaves when no pipe is supported?
I would assume it falls back to the internal git diff locator?
If that would be the case, then there is no need for alternative hook commands.

**Comment by rotemreiss** [comment]
Hi @veewee,
I described the behavior of piping to `lando php` in the issue description: :)
> the execution fails silently instead of just not reading the input from STDIN or something.
In other words - it just does nothing. It seems like the PHP container is starting without anything to run.

The full details are in the Lando issue that was referenced in the issue description as well.

As far as I see, if we are running the command without the pipe (e.g. `lando php ./bin/grumphp 'git:pre-commit' '--skip-success-output'`) then it works great and uses the internal diff, so the only gap is the one described at #144 , don't see any reason why not to add that as a feature since it doesn't suppose to cause any BC issues, performance issues and such..

What do you say? Do I have a green light to proceed with that "feature"?

**Comment by rotemreiss** [comment]
After reading some issues in the issue queue I think that using `hooks_dir` may work with our own custom hooks, right?
Although I hate that solution since it is bad for maintenance reasons (e.g it won't be updated in case Grumphp hooks will be updated).
I still prefer to implement the suggested solution, but I'm waiting for you to decide.

**Comment by veewee** [comment]
I also think a hook preset is the way to go for this.
You could create a lando specific one which we'll ship in this repo. But if they fix the STDIN issue in their repo, it might not be needed anymore. So I think that the preferred solution at this point is to create your own hook for now untill you get more information on the actual issue. If they are not going to solve it, then we could always ship the hook preset. Is that ok for you?

**Comment by rotemreiss** [comment]
You mean to use a hook preset for our repos which won't be contributed to grumphp, right?
I think that Grumphp shouldn't be too specific (like the solution with Vagrant which seems a bit odd to me, but I didn't look deeply into it), and that the solution should be generic like the check for piping support as I suggested.

What are the downsides of the piping check in your opinion (if any..)? Just the complexity factor or something else?

**Comment by veewee** [comment]
Yes that is what I meant. Just for now.
Since some of the hooks can become quite complex, I prefer to keep them in seperate presets.
For example: the vagrant preset is quite complex. It would make no sense to make it generic for every use-case somebody has in mind.

The downside of checking the pipe, is that it doesn't have to happen inside the default preset. Only if you happen to be using lando.

**Comment by rotemreiss** [comment]
Okay, I accept that.
Do you want me to contribute the Lando preset once it's working?

Feel free to close my issue :)
Thanks.

**Comment by veewee** [comment]
Once they solve the stdin pipe, it will work with the current default preset.
If they are not going to fix it and you have something that works, we can indeed merge it in. Feel free to PR at that point.
