### ISSUE TITLE
GrumPhp and PhpUnite

### ISSUE THREAD

**Issue by StephanKrauss** [phpro/grumphp#624]
| Q               | A
| --------------- | ---
| Version         | `0.15`
| Bug?            | no
| New feature?    | no
| Question?       | yes
| Documentation?  | no
| Related tickets | comma-separated list of related tickets

**My configuration**
```yaml
# grumphp.yml

parameters:
  git_dir: .
  bin_dir: vendor/bin
  tasks:
    phpcs:
      standard: PSR2
      ignore_patterns: [./tests/*, ./resources/*, ./database/*, ./bootstrap/*, ./vendor/*]
    phpunite: ~

**Steps to reproduce:**
I have a simple question. How can i start phpunit with grumphp.
When i commit a file i get a complete list of all phpunit commands.

Who can help ?

Your sincerly Stephan

**Comment by jyggen** [comment]
There seems to be a typo in your `grumphp.yml`. The task is named `phpunit`, not `phpunite`.

**Comment by StephanKrauss** [comment]
O.K. i have change the grumphp.yml .
I have insert
phpunit: ~

I see the same effect as before.
How can help with a simple example of phpunit in the grumphp.yml ?


Your sincerly

Stephan

**Comment by janvernieuwe** [comment]
@StephanKrauss Please post your new version.

**Comment by StephanKrauss** [comment]
Hello,

the solution is simple.
In grumphp.yml write

phpunit:
      config_file: C:/<myPath>/<myProject>/phpunite.xml

Your sincerly 

Stephan
