### ISSUE TITLE
GrumPhp only for master and develop branch

### ISSUE THREAD

**Issue by StephanKrauss** [phpro/grumphp#628]
| Q               | A
| --------------- | ---
| Version         | 0.15
| Bug?            | no
| New feature?    | yes
| Question?       | yes
| Documentation?  | no
| Related tickets | comma-separated list of related tickets

Hello,

is there an way to run grumphp only for the master and develop branch ?

Your sincerly

Stephan

**Comment by veewee** [comment]
Hello @StephanKrauss 

That is not possible.
