### ISSUE TITLE
Fatal error for PHPLint with custom "jobs" value 

### ISSUE THREAD

**Issue by mhavelant** [phpro/grumphp#630]
| Q               | A
| --------------- | ---
| Version         | `v0.15.0`
| Bug?            | yes
| New feature?    | no
| Question?       | no
| Documentation?  | no
| Related tickets | comma-separated list of related tickets

**My configuration (relevant parts only)**
```yaml
    phplint:
      exclude: []
      jobs: 5
```

**Steps to reproduce:**
```sh
# Generate empty folder
mkdir tmp
cd tmp
git init
echo "vendor" > .gitignore
pbpaste > grumphp.yml
composer require --dev phpro/grumphp

# Your actions
# Please add the steps on how to reproduce the issue here.

# Run GrumpHP:
git add -A && git commit -m"Test"
# or
./vendor/bin/grumphp run
```

**Result:**
```
Running task 4/9: PhpLint... PHP Fatal error:  Uncaught TypeError: Argument 1 passed to GrumPHP\Process\ProcessUtils::escapeArgument() must be of the type string, integer given, called in /../vendor/phpro/grumphp/src/Process/ProcessFactory.php on line 20 and defined in /../vendor/phpro/grumphp/src/Process/ProcessUtils.php:31
Stack trace:
#0 /../vendor/phpro/grumphp/src/Process/ProcessFactory.php(20): GrumPHP\Process\ProcessUtils::escapeArgument(5)
#1 [internal function]: GrumPHP\Process\ProcessFactory::GrumPHP\Process\{closure}(5)
#2 /../vendor/phpro/grumphp/src/Process/ProcessFactory.php(21): array_map(Object(Closure), Array)
#3 /../vendor/phpro/grumphp/src/Process/ProcessBuilder.php(40): GrumPHP\Process\ProcessFactory::fromArguments(Object(GrumPHP\Collection\ProcessArgumentsCollection))
#4 /../vendor/phpro in /../vendor/phpro/grumphp/src/Process/ProcessUtils.php on line 31
```

**Additionally:**
When using a string value, e.g
```yaml
    phplint:
      exclude: []
      jobs: "5"
```
the error is the following:
```
The option "jobs" with value "5" is expected to be of type "int" or "null", but is of type "string".  
```

**What works:**
Specifying jobs with `~` works, e.g
```yaml
    phplint:
      exclude: []
      jobs: ~
```

**Comment by veewee** [comment]
Hello @mhavelant 

Your YAML file contains a string of "5". This should be just 5 (without the quotes).

**Comment by mhavelant** [comment]
Hi, @veewee ,

As written in the issue, neither `jobs: 5` nor `jobs: "5"` work. The only difference between the 2 is the error message I get.

**Comment by mhavelant** [comment]
More specifically,

- When I use `jobs: 5`, GrumPHP complains that it should be a string
- When I use `jobs: "5"`, GrumPHP complains that it should be an integer or NULL

So my only option is to use `jobs: ~`, but I want to be able to explicitly set the job count.

**Comment by veewee** [comment]
Hi @mhavelant,

Sorry, missed that part for some reason;
Can you verify this works on 15.1 / master?
I pushed a fix recently that casts the param to a string before escaping it: https://github.com/phpro/grumphp/blob/master/src/Process/ProcessFactory.php#L20

**Comment by mhavelant** [comment]
Thanks, I checked it: v0.15.1 seems to have fixed the issue!
