### ISSUE TITLE
PHP Fatal error on composer install

### ISSUE THREAD

**Issue by Afinogen** [phpro/grumphp#633]
| Q               | A
| --------------- | ---
| Version         | `GrumPHP 0.15.0`
| Bug?            | yes
| New feature?    | no
| Question?       | no
| Documentation?  | no
| Related tickets | no

Run
`php composer.phar require --dev phpro/grumphp`

And have

`PHP Fatal error:  Uncaught TypeError: Return value of GrumPHP\Console\Command\ConfigureCommand::pathValidator() must be of the type boolean, string returned in /var/www/html/vendor/phpro/grumphp/src/Console/Command/ConfigureCommand.php:222`

Stack trace:                                                                                                    
```
#0 /var/www/html/vendor/symfony/console/Helper/QuestionHelper.php(57): GrumPHP\Console\Command\ConfigureCommand->pathValidator('.')                                                                                             
#1 /var/www/html/vendor/phpro/grumphp/src/Console/Command/ConfigureCommand.php(132): Symfony\Component\Console\Helper\QuestionHelper->ask(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\StreamOutput), Object(Symfony\Component\Console\Question\Question))                                        
#2 /var/www/html/vendor/phpro/grumphp/src/Console/Command/ConfigureCommand.php(90): GrumPHP\Console\Command\ConfigureCommand->buildConfiguration(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))                                                                                     
#3 /var/www/html/vendor/symfony/console/Command/Command.php(255): GrumPHP\Console\Command\ConfigureCommand-> in /var/www/html/vendor/phpro/grumphp/src/Console/Command/ConfigureCommand.php on line 222
```

`public function pathValidator($path): bool`

I think there is an incorrect return type

**Comment by oallain** [comment]
I got the same error.
She was introduced in the commit https://github.com/phpro/grumphp/commit/c87aa535d97a3e9e6c1803de5db6c1bd74989383

**Comment by oallain** [comment]
Apologies, this commit fix this error :+1:

**Comment by veewee** [comment]
Thanks for reporting. it is indeed fixed on master. Release will follow soon
