### ISSUE TITLE
 phpstan , ignore files under ./tests

### ISSUE THREAD

**Issue by StephanKrauss** [phpro/grumphp#635]
| Q               | A
| --------------- | ---
| Version         | `0.15`
| Bug?            | no
| New feature?    | no
| Question?       | yes

Hello,

in my project i use phpunit.
The tests are under ./tests/ in Subfolder.
I have integrated 
phpstan in the grumphp.yml .
I will ignore the tests under ./tests

Here the part of my grumphp.yml.

----------------------------
phpstan:
      triggered_by: ['php']
      level: 0
      ignore_patterns: [./tests/App/*/*, ./public/*, ./config/*]
----------------------------------

When i start: ./vendor/bin/grumphp run

grumphp checked my test-files.

Who can help ?

Your sincerly

Stephan

**Comment by veewee** [comment]
Hello @StephanKrauss,

It accepts any argument from the symfony/finder `notPaths()` method:
https://symfony.com/doc/current/components/finder.html#path
