### ISSUE TITLE
Add codeception task

### ISSUE THREAD

**Issue by Anahkiasen** [phpro/grumphp#65]
Would it be possible to add a Codeception task? It's one of the major testing frameworks with PHPUnit and PHPSpec, would love to have it in Grumphp

**Comment by veewee** [comment]
It sure is possible to add a Codeception task. I haven't used it before so I don't know the CLI of codeception. Feel free to create a PR or give some additional information about how it shoud be implemented / configured.

Thanks!

**Comment by adam-paterson** [comment]
@Anahkiasen get back to rocketeer! I'm happy to add the Codeception task

**Comment by adam-paterson** [comment]
#69 added!

**Comment by veewee** [comment]
Merged #69.
