### ISSUE TITLE
GrumPHP in submodules

### ISSUE THREAD

**Issue by PrzemekTurek2017** [phpro/grumphp#659]
| Q               | A
| --------------- | ---
| Version         | `0.15.2`
| Bug?            | no
| New feature?    | no
| Question?       | yes
| Documentation?  | yes
| Related tickets | https://github.com/phpro/grumphp/issues/109

As it said  [here](https://github.com/phpro/grumphp/blob/master/doc/issues/grumphp-is-not-working-with-submodules.md) "GrumPHP is not working **with** submodules", but it will work **inside** submodules if correct `git_dir` is specified : `git_dir: ../.git/modules/{module_name}`. So maybe doc should be extended with above info ?

**Comment by veewee** [comment]
Thanks @PrzemekTurek2017 
That is correct. 
I've added a test in https://github.com/phpro/grumphp/pull/644 and removed the documentation file.
