### ISSUE TITLE
How to make grumphp work only in a subdirectory?

### ISSUE THREAD

**Issue by bartvastgoed** [phpro/grumphp#660]
| Q               | A
| --------------- | ---
| Version         |GrumPHP 0.15.2
| Bug?            | no
| New feature?    | no
| Question?       | yes
| Documentation?  | no
| Related tickets | comma-separated list of related tickets

How to make grumphp work only in a subdirectory? (where installed)

example folder structure:
- src
- cache
- ansible
- mysymfony4codebase
- someothercodebase
- public
- .git

I'm using a vagrant box for this entire codebase.

Where "mysymfony4codebase" is an entire (symfony 4) codebase on its own. This is where i installed grumphp trough composer, but it doesnt seem to work as i'm trying to get it to detect some bad smells.

Code that should trigger grumphp
```
class ProductController extends AbstractController
{
    /**
     * @Route("/product", name="product")
     */
    public function index() {





        echo " aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa";
        return $this->render('product/index.html.twig', [ 'controller_name' => 'ProductController', ]);
    }
}
```

my grumphp.yml:
```
parameters:
    git_dir: .
    bin_dir: vendor/bin
    hooks_preset: vagrant
    tasks: {  }
```

P.s. would having multiple composers be an issue?

Command i'm running:
```
mysymfony4codebase/vendor/bin/grumphp run --config "/vagrant/mysymfony4codebase/grumphp.yml" 
```

However it seems like no matter what (even wrong paths) the --config param doesnt seem to work

**Comment by veewee** [comment]
Hello @bartvastgoed,

Your grumphp.yml does not contain any task. That is why it is not complaining about anything.

That folder structure should be possible. We've pushed some improvements to master a couple of weeks a go which are not released yet. So you might also check those out.
