### ISSUE TITLE
Why is there --report-json hard-coded in Phpcs.php

### ISSUE THREAD

**Issue by hkirsman** [phpro/grumphp#662]
https://github.com/phpro/grumphp/blob/master/src/Task/Phpcs.php#L86

When I enable phpcs it outputs full report which is default by phpcs and it can also be configured from grumphp. Now the problem is that after the human readable full report, it also outputs json report. I don't see any other reason for that than it's there by mistake.

Or is there any reason for this. Screenshot:
https://www.upload.ee/image/10354579/DeepinScreenshot_select-area_20190814171026.png

**Comment by jyggen** [comment]
The output from PHP_CodeSniffer is handled by [GrumPHP\Formatter\PhpcsFormatter](https://github.com/phpro/grumphp/blob/master/src/Formatter/PhpcsFormatter.php) which does expect the output to look like it does in the provided screenshot. For some reason the formatter is not able to extract and parse the JSON though and instead leaves the output as is, which results in the behaviour you're seeing.

Your OS-, PHP-, GrumPHP- and PHP_CodeSniffer version, as well as your `grumphp.yml` could be useful to debug this further.

**Comment by hkirsman** [comment]
I'm not sure what was wrong but now that I've started off with clean setup for GrumPHP and it seems to work fine. I'll report back when I see it again. OS is Linux Manjaro.
