### ISSUE TITLE
Support request: can you access grumphp.yml root level params from tasks?

### ISSUE THREAD

**Issue by hkirsman** [phpro/grumphp#673]
We are adding paths to our tasks where it should scan the code when 'grumphp run' code has executed. Duplicating the same variable for all tasks seems tedious. So we would have something like this:

    parameters:
      run_on: web/modules/custom

and then all of the tasks would read that parameter. 

edit: i guess the answer is that all the existing variables have getters in https://github.com/phpro/grumphp/blob/master/src/Configuration/GrumPHP.php  and the container itself is private so not possible. Still would kike to hear your comment.

Thank you!

**Comment by veewee** [comment]
Hello @hkirsman,

You can use everything that the symfony container allows you to.
Depending on your case, there are some options.

A quick list from good idea to probably a bad idea:

- (Set the project path to that directory see : https://github.com/phpro/grumphp/blob/master/doc/installation/exotic.md)
- You can point to the parameter from another location (see example underneath)
- You can inject the parameter in the tasks constructor, setter, ...
- You can do some transformations with a compiler pass
- ...


example:

```yml
parameters:
  run_on: web/modules/custom
  tasks:
    phpcs:
        whitelist: [%run_on%]
```

(The same technique is being used while using conventions: https://github.com/phpro/grumphp/blob/master/doc/conventions.md)
