### ISSUE TITLE
Wrong path for Composer bin-dir

### ISSUE THREAD

**Issue by mattheo-geoffray** [phpro/grumphp#677]
| Q               | A
| --------------- | ---
| Version         | `0.16.0`
| Bug?            | yes/no
| New feature?    | yes/no
| Question?       | yes/no
| Documentation?  | yes/no
| Related tickets | comma-separated list of related tickets

Since the version `0.16.0` and the GuessPath we have the possibility to override GrumPHP with environment variables as in `\GrumPHP\Locator\GuessedPathsLocator::locate`   
The ComposeFile does not take care of this variable for the `bin-dir` value and try to load binaries from an other Composer vendor bin directory

**My configuration**
```yaml
|- .git/
|- magento
       |- src
            |- composer.json
            |- vendor/bin/phpcs
|- composer.json
|- vendor/bin/phpcs
|- grumphp.yml
```

**Steps to reproduce:**
Modify a file
```sh
git add .
git commit -m "test"
```

**Result:**
GrumPHP is adding bin dir to path using
```
// add the bin dir to the PATH to make local binaries of deps usable in scripts
$binDir = realpath($this->getBinDir());
```
with this it takes `/path/to/project/magento/src/vendor/bin` and not `/path/to/project/vendor/bin`

**Comment by veewee** [comment]
Hallo @mattheo-geoffray 

The problem starts with using 2 `composer.json` files in your project of course :)
We currently assume you only have one composer file and only one bin dir.
Is there any reason why you do this?
(However: multiple bin dirs are possible by changing your PATH env var)

You should be able to get it to work by pointing to the correct `GRUMPHP_COMPOSER_DIR`.
This way the bin-dir of the selected composer file is used.

FYI: You can debug the path selection by passing the verbose flags to the command line.

You are right that the composerFile does not register the correct path in the case when you overwrite the bin_dir. I'll take a look what I can do about that. It is some very old hack to make sure cli mode works exactly the same as the composer plugin. I can most likely remove this code once #675 is ready.

**Comment by veewee** [comment]
FYI : The bin-dir issue you mentioned should be fixed in PR above. Feel free to test it out.

Still curious about how and why you work with 2 composer files though.

**Comment by mattheo-geoffray** [comment]
@veewee Thank for you quick and complete answer!

The reason why we are using two composer file is because we want to decorrelate the local test part and the framework part so that we can manage both more easily.

But in way you're right GrumPHP is a dependency of the project so there is no reason to not include it in the require-dev part of it!

If you agree we can close this issue 🙂

**Comment by veewee** [comment]
In that case, this one might be something for you : https://github.com/bamarni/composer-bin-plugin
Let's close this for now.

**Comment by mattheo-geoffray** [comment]
@veewee Oh nice thank you for the tip I will take a look at it! 🙂
