### ISSUE TITLE
Is it possible to modify commit message?

### ISSUE THREAD

**Issue by TheRatG** [phpro/grumphp#688]
| Q               | A
| --------------- | ---
| Version         | GrumPHP 0.16.1
| Bug?            | no
| New feature?    | no
| Question?       | yes
| Documentation?  | no

Is it possible to modify commit message? For example automatically prepend git commit with a branch name.

**Comment by oallain** [comment]
Not to my knowledge.

We have a task to [control the format of a commit message](https://github.com/phpro/grumphp/blob/master/doc/tasks/git_commit_message.md), but nothing to prefix the name of the branch.
[Git commit message](https://github.com/phpro/grumphp/blob/master/doc/tasks/git_commit_message.md)

It may be interesting to add an option to this task to add this feature.
Would you like to make a pull request?

**Comment by veewee** [comment]
Changing the commit message from grumphp won't be easy. Especially inside the vagrant specific hook. You need to alter a temporary file for that. Therefor I'dd suggest to keep GrumPHP for validating the commit message.

It's a better option to use the `prepare-commit-msg` git hook to change the commit message. This is not something that is supported by GrumPHP. 
More info about how that hook works: https://medium.com/@jake.henningsgaard/exploring-git-customizing-commit-messages-1a4ecb4dca69

**Comment by TheRatG** [comment]
> Changing the commit message from grumphp won't be easy. Especially inside the vagrant specific hook. You need to alter a temporary file for that. Therefor I'dd suggest to keep GrumPHP for validating the commit message.
> 
> It's a better option to use the `prepare-commit-msg` git hook to change the commit message. This is not something that is supported by GrumPHP.
> More info about how that hook works: https://medium.com/@jake.henningsgaard/exploring-git-customizing-commit-messages-1a4ecb4dca69

Thanks for answer
