### ISSUE TITLE
Does not work at all

### ISSUE THREAD

**Issue by piotrkochan** [phpro/grumphp#690]
| Q               | A
| --------------- | ---
| Version         | `GrumPHP 0.14.3`
| Bug?            | yes
| New feature?    | no
| Question?       | no
| Documentation?  | no
| PHP Version | PHP 5.6.40-8+ubuntu18.04.1+deb.sury.org+1 (cli) 

**My configuration**

Default

**Steps to reproduce:**

I'am adding random typos in .php files, then stage them and commit. Like "sdugfsduhf"

# Your actions
# Please add the steps on how to reproduce the issue here.

git add file.php
git commit -m "my commit" 

or just `./vendor/bin/grumphp run`
```

**Result:**
```
       _    _ _                         _ _
      / \  | | |   __ _  ___   ___   __| | |
     / _ \ | | |  / _` |/ _ \ / _ \ / _` | |
    / ___ \| | | | (_| | (_) | (_) | (_| |_|
   /_/   \_\_|_|  \__, |\___/ \___/ \__,_(_)
                  |___/
```

**Comment by janvernieuwe** [comment]
Can you share your `grumphp.yml` configuration file?
Did you define any tasks for grumPHP to check?

**Comment by piotrkochan** [comment]
My fault, I've just haven't configured anything :)
