### ISSUE TITLE
Git branch name task

### ISSUE THREAD

**Issue by paul-gene** [phpro/grumphp#699]
| Q               | A
| --------------- | ---
| Version         | 0.16.2
| Bug?            | no
| New feature?    | no
| Question?       | yes
| Documentation?  | no
| Related tickets | n/a

How can I have multiple whitelist entries, where the branch name just needs to match one?

If I have two, it fails when the branch name doesn't match one of the whitelist regexes.

eg 

```
git_branch_name:
      whitelist: ['release/*', '/\w+\-\d+/']
```

this should match for `release/1.0.0` but it fails due to the second check, which allows branches named `JIRA-123`

**Comment by oallain** [comment]
Hello @paul-gene 

You can use only one regex to doo this, like :
`^((feature|fix|release)\/[a-z0-9-]+)$|^(JIRA-[a-z0-9-]+)$`

You can test here https://regex101.com/r/B7vseI/1

Have a nice day :+1:
