### ISSUE TITLE
Protected branch check

### ISSUE THREAD

**Issue by benr77** [phpro/grumphp#703]
First of all, thank you for a wonderful package. GrumPHP has been a great addition to my tool set.

Question - is it possible to use one of the tasks to prohibit committing to a particular git branch?

For example, in our workflow I only want to permit merge or rebase on to master branch. However, sometimes people accidentally commit directly to master and it's a pain to fix up.

Thanks

**Comment by veewee** [comment]
Hello @benr77,

You can use this one for that:
https://github.com/phpro/grumphp/blob/master/doc/tasks/git_branch_name.md

Users can skip the git hook, so it's better to configure these things on your git service instead.
