### ISSUE TITLE
Fatal error: Uncaught TypeError: Argument 1 passed to Symfony\Component\Process\Process::__construct() must be of the type array, string given

### ISSUE THREAD

**Issue by dhurlburtusa** [phpro/grumphp#706]
Version: 0.17.0
Bug: yes
Php Version: 7.3.5
OS: Windows 10
Symfony/Process Version: 5.0

I get the following error whenever grumphp is installed.

```
Fatal error: Uncaught TypeError: Argument 1 passed to Symfony\Component\Process\Process::__construct() must be of the type array, string given, called in C:\...\vendor\phpro\grumphp\src\Process\ProcessFactory.php on line 25 and defined in C:\...\vendor\symfony\process\Process.php:140
Stack trace:
#0 C:\...\vendor\phpro\grumphp\src\Process\ProcessFactory.php(25): Symfony\Component\Process\Process->__construct('"C:\\Program Fil...')
#1 C:\...\vendor\phpro\grumphp\src\Locator\GitWorkingDirLocator.php(30): GrumPHP\Process\ProcessFactory::fromArguments(Object(GrumPHP\Collection\ProcessArgumentsCollection))
#2 C:\...\vendor\phpro\grumphp\src\Locator\GuessedPathsLocator.php(153): GrumPHP\Locator\GitWorkingDirLocator->locate()
#3 C:\...\vendor\phpro\grumphp\src\Locator\GuessedPathsLocator.php(47): GrumPHP\Locator\GuessedPat in C:\...\vendor\symfony\process\Process.php on line 140
GrumPHP can not sniff your commits! (invalid-exit-code)
```

It happens when I run `composer install` in project that already has

```
	"require-dev": {
		"phpro/grumphp": "^0.17.0"
	},
```
in the `composer.json`.

It happens when I run `composer require --dev phpro/grumphp` on a project without grumphp installed.

In general, it seems to happen whenever I run a grumphp command.

I added the following composer script to `composer.json`:

```
	"scripts": {
		"grumphp:git:init": "grumphp git:init"
	}
```
and then ran `composer grumphp:git:init`

The effect is that the git hooks are not installed.

Based on the error and a comment I found in the code, it looks like Symfony's Process constructor is being called incorrectly.

I have a PR almost ready to go. I'll associate it with this issue shortly.

**Comment by dhurlburtusa** [comment]
After further research, the error only seems to occur when using Symfony/Process 5.x. So, a temporary work around is to add , something like `"symfony/process": "^4.0"` to `"require-dev"` or `"require"` in `composer.json`.

**Comment by cmen** [comment]
https://github.com/symfony/symfony/blob/master/UPGRADE-5.0.md#process

**Comment by Tofandel** [comment]
For anyone still wondering, this thread being the first on google with this error message

This issue is because `composer` version 2.3+ requires `symfony/process^5` itself, but your project also has a dependency on symfony/process^4 somewhere, composer loads it first and when your project tries to use it, expecting v4 but using v5 it triggers the error

You have to use a composer.phar version in the 2.2 range to be able to update your dependencies normally
