### ISSUE TITLE
Failed opening required 'phar://grumphp.phar/.box/bin/check-requirements.php'

### ISSUE THREAD

**Issue by brownrl** [phpro/grumphp#724]
| Q               | A
| --------------- | ---
| Version         | `doesn't run`
| Bug?            | yes
| New feature?    | no
| Question?       | no
| Documentation?  | no
| Related tickets |  

Doesn't run, file missing in phar archive.

**My configuration**
```yaml
# grumphp.yml
# Please add a copy of your grumphp.yml file.
```

**Steps to reproduce:**
```sh
# Generate empty folder
mkdir tmp
cd tmp
git init
echo "vendor" > .gitignore
pbpaste > grumphp.yml
composer require --dev phpro/grumphp
./vendor/bin/grumphp
```

**Result:**
```
Fatal error: require(): Failed opening required 'phar://grumphp.phar/.box/bin/check-requirements.php' (include_path='.:/usr/local/Cellar/php@7.2/7.2.26/share/php@7.2/pear') in /........./vendor/phpro/grumphp-shim/grumphp on line 9
```

**Comment by veewee** [comment]
Thanks for reporting!
It was also logged+fixed in the shim repo.
Will handle it soon! 

(https://github.com/phpro/grumphp-shim/issues/3)
