### ISSUE TITLE
Respect core.commentChar config in CommitMessage::getCommitMessageLinesWithoutComments()

### ISSUE THREAD

**Issue by donquixote** [phpro/grumphp#729]
| Q               | A
| --------------- | ---
| Version         | GrumPHP 0.15.2
| Bug?            | no
| New feature?    | yes
| Question?       | no
| Documentation?  | no
| Related tickets | 

CommitMessage::getCommitMessageLinesWithoutComments() extracts the part of a commit message which is not a comment.

The function assumes that all comments start with '#'.
This means it won't work if the core.commentChar config in git is something else.

E.g. I like to use ';' as comment char, which makes it possible / easier to begin your commit message with '#' without it being ignored.

```
git config core.commentChar ";"
git commit -m"#55: Add more tests."
```

**Comment by veewee** [comment]
Thanks for suggesting!
Fixed in #808
