### ISSUE TITLE
Use double quotes instead of simple ones for git_hook_variables argument escaping

### ISSUE THREAD

**Issue by Maxooo** [phpro/grumphp#733]
| Q               | A
| --------------- | ---
| Version         | GrumPHP 0.17.2
| Bug?            | yes
| New feature?    | no
| Question?       | no
| Documentation?  | no
| Related tickets | 

When using `git_hook_variables` parameter, you may also need to use variables inside your configured values. This seems to be impossible to do as the replaced `$(EXEC_GRUMPHP_COMMAND)` variable in the hooks template is replaced by parts escaped with simple quotes (`'`) instead of the double ones (`"`).

**My configuration**

This use case can be found in the [parameters documentation section](https://github.com/phpro/grumphp/blob/master/doc/parameters.md) with the docker implementation. So please use the following configuration : 

```yaml
parameters:
    git_hook_variables:
        EXEC_GRUMPHP_COMMAND: 'docker run --rm -it -v $(pwd):/grumphp -w /grumphp webdevops/php:alpine'
``` 

**Steps to reproduce:**

```sh
# Generate an empty folder
mkdir tmp
cd tmp
git init
echo "vendor" > .gitignore
# Please copy paste the configuration (e.g. previous section) and run the following command
pbpaste > grumphp.yml
composer require --dev phpro/grumphp:0.17.2
```
At this state you do not need much more to anticipate the error. Please open one of the  `.git/hooks/pre-commit` or `.git/hooks/commit-msg` hook files and notice the simple escaping on the GrumPHP running command (last line).

```bash
# .git/hooks/pre-commit

# Run GrumPHP
(cd "./" && printf "%s\n" "${DIFF}" | 'docker' 'run' '--rm' '-it' '-v' '$(pwd):/grumphp' '-w' '/grumphp' 'webdevops/php:alpine' 'vendor/phpro/grumphp/bin/grumphp' 'git:pre-commit' '--skip-success-output')
```
The second file is more interesting as it use variables in the GrumPHP command part (`$GIT_USER`, `$GIT_EMAIL` and `$COMMIT_MSG_FILE`) and they are both well escaped with double quotes (`"`).

```bash
# .git/hooks/commit-msg

# Run GrumPHP
(cd "./" && printf "%s\n" "${DIFF}" | 'docker' 'run' '--rm' '-it' '-v' '$(pwd):/grumphp' '-w' '/grumphp' 'webdevops/php:alpine' 'vendor/phpro/grumphp/bin/grumphp' 'git:commit-msg' "--git-user='$GIT_USER'" "--git-email='$GIT_EMAIL'" "$COMMIT_MSG_FILE")
```

If you want to see the error you can go forward and run this command : 

```bash
git add -A && git commit -m"Test"
```
If you have (like me) the following error `the input device is not a TTY` this is - may be - because the documentation needs an update.
Update your grumphp.yml file configuration and remove the docker `-t` parameter to obtain the following configuration : 

Then run the command : 

```
# Tell GrumPHP to your re-generate hooks
vendor/bin/grumphp git:init
# And the previous one again 
git add -A && git commit -m"Test"
```

**Result:**

```bash
docker: Error response from daemon: create $(PWD): "$(PWD)" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path.
See 'docker run --help'.
```

**Fix suggestion:**

Update the [`GrumPHP\Process\ProcessUtils`](https://github.com/phpro/grumphp/blob/ecfc01920fb5733193a41da292e8abb702b6d55d/src/Process/ProcessUtils.php#L28)  `escapteArgument` method like this : 

```php
public static function escapeArgument(string $argument): string
{
        if ('\\' !== DIRECTORY_SEPARATOR) {
            return '"'.str_replace("'", "'\\''", $argument).'"';
            // return "'".str_replace("'", "'\\''", $argument)."'";
        }
        ...
```

This fix is in fact a wrong idea as it break the existing behaviors with double quoted commands. Moreover, this par of the code is extracted from the Symfony component and it shouldn't be modified as we would like to remove it once the Symfony's Process will accept an array of parameters.

**Comment by veewee** [comment]
Fixed in #780
