### ISSUE TITLE
Configurate multiple docker containers.

### ISSUE THREAD

**Issue by benndt** [phpro/grumphp#735]
| Q               | A
| --------------- | ---
| Version         | 0.17.2
| Bug?            | no
| New feature?    | no
| Question?       | yes
| Documentation?  | no
| Related tickets | 

I used a php-cli container for php and a node container for yarn / npm. 

If I want to use the npm tasks my php-cli container does not know npm. Is there a way to specify two docker containers? Or to change the EXEC_GRUMPHP_COMMAND per task?

**Comment by veewee** [comment]
Hello @benndt 

This is not possible. The git hook runs one command that executes all configured tasks.
However, you could configure multiple shell tasks that trigger docker commands or create seperate tasks for the things you want to do.
