### ISSUE TITLE
Workflow for docker container

### ISSUE THREAD

**Issue by pimjansen** [phpro/grumphp#736]
| Q               | A
| --------------- | ---
| Version         | n/a
| Bug?            | no
| New feature?    | no
| Question?       | yes
| Documentation?  | no
| Related tickets | n/a

# Question

I am using GrumPHP for some while now and i actually love it since it reduces a lot of stress on my build agent since i can catch such things upfront. At this point im in the middle of a migration towards `docker` and i am struggling a bit with the workflow.

I have a local git clone on my system. Further i have a single PHP container running which holds allt he code. The main problem is that when running composer install (inside the container due to version constraints and depedencies) the `.git` folder is not inside the container since the .git folder is excluded from the copy (never push git inside a container). 

So the main problem is, grumphp cant reach the hooks so at the end there are none. Overall i can run commands pretty easy by running them from my local machine inside the container:
```sh
docker-compose exec -T phpfpm php ./vendor/bin/phpcs
```

Any tips on how to deal with this or someone that already found a workflow that fits?

Thanks

**Comment by veewee** [comment]
The one suggested in the docs works for me:
https://github.com/phpro/grumphp/blob/master/doc/parameters.md

```
        EXEC_GRUMPHP_COMMAND: 'docker-compose run --rm --no-deps php'
```

You'll need to rerun the `git:init` command after changing the parameter.
The container will need the git executable and .git folders in orde to make this work

**Comment by gbobts** [comment]
@veewee it seems that the whole .git directory has to be on the container ? If so, it seems it could cause overhead for mutagen. Unless some specific mutagen configuration is used and only some of the .git content is needed (.git/COMMIT_EDITMSG and .git/hooks ?)

**Comment by veewee** [comment]
@gbobts We're using it in our pojects that way and it works fine (including mutagen). 
You can finetune it however you please, but grumphp uses git to build diffs and  grab commit messages, subtrees, ... - so as long if that works, you should be fine.
