### ISSUE TITLE
Per user config / Params

### ISSUE THREAD

**Issue by immoreel** [phpro/grumphp#738]
| Q               | A
| --------------- | ---
| Version         | GrumPHP 0.17.2
| Bug?            | no
| New feature?    | no
| Question?       | yes
| Documentation?  | no

I was wondering if it's possible to have per user configurations so my coworker can use Docker and another can use Vagrant and a third could use native applications?

Something like `grumphp.local.yml` for instance...

Thanks!

**Comment by fabianderijk** [comment]
I've got the same issue. This would be a nice one to have!

**Comment by veewee** [comment]
This is already possible by using a dist file or by finetuning a convention. docs:

* https://github.com/phpro/grumphp#configuration
* https://github.com/phpro/grumphp/blob/master/doc/conventions.md

**Comment by johandenhollander** [comment]
Pardon my French but I don't really get how this is supposed to work?

How can two persons using the same git repository still have a different Grumphp execution while they have the same grumphp.yml?
One executes like this: 
git_hook_variables:
      EXEC_GRUMPHP_COMMAND: 'exec'

While another person would want to use:
git_hook_variables:
    EXEC_GRUMPHP_COMMAND: 'docker-compose run --rm --no-deps php'

They way we have it setup right now causes some colleagues that have no local php install (using docker) to have to replace their git hooks from backup sometimes.

**Comment by veewee** [comment]
You can use a `grumphp.yaml.dist` file which you can fine-tune in a `grumphp.yaml` file.
If you don't copy the dist file, GrumPHP will use the defaults configured inside that dist file.
If you do have a `grumphp.yaml` file, that file will be taken over the dist file.

It does require the user to overwrite the config and let grumphp regenerate the git hooks.
