### ISSUE TITLE
Invalid default ruleset for twig

### ISSUE THREAD

**Issue by a-menshchikov** [phpro/grumphp#746]
| Q               | A
| --------------- | ---
| Version         | 0.18.0
| Bug?            | yes
| New feature?    | no
| Question?       | no
| Documentation?  | yes
| Related tickets |

Ruleset `FriendsOfTwig\Twigcs\Ruleset\Official` is outdated. Actual default ruleset is `Allocine\Twigcs\Ruleset\Official`.

**Comment by oallain** [comment]
Hi @a-menshchikov ,

This is already the case, you can see the PR here https://github.com/phpro/grumphp/pull/657

Have you update your GrumPHP version ?

**Comment by a-menshchikov** [comment]
Hello @oallain .

When I'm doing `composer require friendsoftwig/twigcs --dev`, I have allocine/twigcs package.
Thus this PR seems like a bug.

**Comment by veewee** [comment]
![Screen Shot 2020-03-19 at 07 40 17](https://user-images.githubusercontent.com/1618158/77038807-eda0f580-69b4-11ea-8dc5-c61951b558b8.png)

Can you try to remove the allocine package and use the friendsoftwig package instead?

**Comment by a-menshchikov** [comment]
@veewee I don't use allocine package. As I wrote above, I run `composer require friendsoftwig/twigcs --dev` in cli. (I've tried to run `composer clear-cache` before.)

**Comment by veewee** [comment]
In that case the `FriendsOfTwig\Twigcs\Ruleset\Official` is the default right?

**Comment by a-menshchikov** [comment]
To be more precise, I will say this: now composer installs allocine version of twigcs instead of friendsoftwig's. And as I'm concerned, this is the wrong behavior.
But now I have no `FriendsOfTwig\Twigcs\Ruleset\Official` class and I have to specify `ruleset: 'Allocine\Twigcs\Ruleset\Official'` in grumphp.yml explicitly.

**Comment by veewee** [comment]
This doesn't look like a GrumPHP issue then:

```
composer require friendsoftwig/twigcs --dev

composer show                                                                                                                                                                                                                                       
friendsoftwig/twigcs      v3.2.2  Checkstyle automation for Twig
```

You might be able to validate why the allocine package is being installed by running

```
composer why allocine/twigcs
```

I hope you find a solution for your problem soon!

**Comment by a-menshchikov** [comment]
This issue had solved by installing twigcs 4.0 (beta), because 3.2.2 still has allocine as vendor name (https://github.com/friendsoftwig/twigcs/blob/v3.2.2/composer.json#L2).

Maybe this fact should be noted in docs?

**Comment by veewee** [comment]
This is rather something that should be fixed in the package.
We could add it to the docs, but it seems like a temporary issue until 4 gets released?
Another option is to set the default rule to "null" and fall back to the rule that is configured internally in the package. That looks like a better approach if the tool supports it.

**Comment by a-menshchikov** [comment]
Yes, that solution will be better.

**Comment by oallain** [comment]
Yeah, twigcs is in v4beta4, stable version will be released soon I think.

**Comment by veewee** [comment]
Closing since this issue will solve itself at some point eventually :)
