### ISSUE TITLE
Modified files are not checked when using git commit -a

### ISSUE THREAD

**Issue by bhelm** [phpro/grumphp#751]
| Q               | A
| --------------- | ---
| Version         | 0.18.0
| Bug?            | yes
| New feature?    | maybe

I have noticed that using git commit -a causes grumphp to not include the modified-but-not-added files that will be committed by using -a.

This is because git diff --staged is used within the hook and this causes grumphp to only look at staged files (that were added by git add ...).

End of story: when using -a, all modified but not staged files get committed without being checked by grumphp. It is also not clear to the user that this happens.

from the git docs:
>        -a, --all
>           Tell the command to automatically stage files that have been modified and deleted, but new files you have not told Git about are not affected.

while looking for ideas how to fix this, i only came up with ```cat /proc/$PPID/cmdline``` to parse the git commandline to detect the usage of -a within the hook. i wonder if ther would be a better way to detect the usage of -a within the hook.

**Comment by veewee** [comment]
The `-a` flag does some funky things inside git:

https://github.com/phpro/grumphp/blob/master/resources/hooks/local/commit-msg#L12-L13

The diff in this git hook does include the files. However while parsing the git diff from inside the php process, the diff results in the one before running the commit command. It looks like it is doing something in memory.

Therefor we've added it to the git hooks.
It should do the trick...


Can you provide some additional information about your grumphp.yml file and setup?
If e.g. you are using a custom hook, other hook preset or an executable that doesn't handle stdin : it might not work.

**Comment by bhelm** [comment]
thank you for the feedback.

it is related to running grumphp in a docker container. i should have checked this before. 
When using the default hook.
with
```
    git_hook_variables:
        EXEC_GRUMPHP_COMMAND: 'docker-compose run --rm --no-deps php-fpm'
```
modified files are ignored when using -a. without docker, it works.

the diff is passed correctly to the docker container (i have replaced grumphp with cat in the hook for verification).
is grumphp possibly doing git diff calls itself?

i had to include git in my container to get grumphp to work, without git in the path, i get this error:
```
Fatal error: Uncaught TypeError: Argument 1 passed to GrumPHP\Collection\ProcessArgumentsCollection::forExecutable() must be of the type string, null given, called in /application/vendor/phpro/grumphp/src/Locator/GitWorkingDirLocator.php on line 26 and defined in /application/vendor/phpro/grumphp/src/Collection/ProcessArgumentsCollection.php on line 12

TypeError: Argument 1 passed to GrumPHP\Collection\ProcessArgumentsCollection::forExecutable() must be of the type string, null given, called in /application/vendor/phpro/grumphp/src/Locator/GitWorkingDirLocator.php on line 26 in /application/vendor/phpro/grumphp/src/Collection/ProcessArgumentsCollection.php on line 12

Call Stack:
    0.0001     772776   1. {main}() /application/vendor/phpro/grumphp/bin/grumphp:0
    0.0001     773096   2. {closure:/application/vendor/phpro/grumphp/bin/grumphp:8-51}() /application/vendor/phpro/grumphp/bin/grumphp:51
    0.0092    2403512   3. GrumPHP\Configuration\ContainerFactory::build() /application/vendor/phpro/grumphp/bin/grumphp:46
    0.0092    2403512   4. GrumPHP\Configuration\ContainerFactory::guessPaths() /application/vendor/phpro/grumphp/src/Configuration/ContainerFactory.php:21
    0.0106    2598632   5. GrumPHP\Locator\GuessedPathsLocator->locate() /application/vendor/phpro/grumphp/src/Configuration/ContainerFactory.php:40
    0.0106    2598672   6. GrumPHP\Locator\GuessedPathsLocator->safelyLocateGitWorkingDir() /application/vendor/phpro/grumphp/src/Locator/GuessedPathsLocator.php:47
    0.0106    2598672   7. GrumPHP\Locator\GitWorkingDirLocator->locate() /application/vendor/phpro/grumphp/src/Locator/GuessedPathsLocator.php:153
    0.0111    2668840   8. GrumPHP\Collection\ProcessArgumentsCollection::forExecutable() /application/vendor/phpro/grumphp/src/Locator/GitWorkingDirLocator.php:26
```

here is my php container and grumphp config:
https://pasti.ng/7GH6bCH1jUt

**Comment by veewee** [comment]
It only does the diff itself if the stdin cannot be read (which is the case I presume).
