### ISSUE TITLE
Git commit message regex bug

### ISSUE THREAD

**Issue by mechanicalgux** [phpro/grumphp#757]
https://github.com/phpro/grumphp/blob/b8354000dc6e177ab1e77c06817876f11bb6c879/src/Task/Git/CommitMessage.php#L354

This regex should be:
```php
$scopesPattern = '(:\s|(\((?:' . $scopes . ')\)?:\s))';
````

In the current form it doesn't match as the closing parenthesis is part of the last scope in list.
So the scopes need to be wrapped in a non-capturing group.

Test it:
Failing (current): https://regex101.com/r/JMehsC/2
Working (new): https://regex101.com/r/OyzLb1/1

**Comment by veewee** [comment]
Hello @mechanicalgux,

Thanks for reporting! Would you like to create a PR for this?

**Comment by veewee** [comment]
Fixed in #808
