### ISSUE TITLE
Any ideas on GrumPHP as a paid service?

### ISSUE THREAD

**Issue by keremcankaya0** [phpro/grumphp#761]
| Q               | A
| --------------- | ---
| Version         | `vendor/bin/grumphp -V`
| Bug?            | no
| New feature?    | no
| Question?       | no
| Documentation?  | no
| Related tickets | 

Is there any plan to serve these functionalities as a SAAS in the future like StyleCI with Github integration?

**Comment by veewee** [comment]
Not for the moment. You can already run GrumPHP in any CI environment you wish!
