### ISSUE TITLE
GrumPHP 0.18 crashes with symfony/event-dispatcher 3 

### ISSUE THREAD

**Issue by prudloff-insite** [phpro/grumphp#781]
| Q               | A
| --------------- | ---
| Version         | GrumPHP 0.18.1
| Bug?            | yes
| New feature?    | no
| Question?       | no
| Documentation?  | no
| Related tickets | 

**My configuration**
I can reproduce with an empty configuration file.

**Steps to reproduce:**
```sh
# Generate empty folder
mkdir tmp
cd tmp
git init
composer require phpro/grumphp:^0.18 symfony/event-dispatcher:^3
./vendor/bin/grumphp run
```

**Result:**
```
PHP Fatal error:  Uncaught TypeError: Argument 2 passed to Symfony\Component\EventDispatcher\EventDispatcher::dispatch() must be an instance of Symfony\Component\EventDispatcher\Event or null, instance of GrumPHP\Event\RunnerEvent given, called in /home/pierre/workspace/test/vendor/phpro/grumphp/src/Event/Dispatcher/Bridge/SymfonyEventDispatcher.php on line 32 and defined in /home/pierre/workspace/test/vendor/symfony/event-dispatcher/EventDispatcher.php:37
Stack trace:
#0 /home/pierre/workspace/test/vendor/phpro/grumphp/src/Event/Dispatcher/Bridge/SymfonyEventDispatcher.php(32): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('grumphp.runner....', Object(GrumPHP\Event\RunnerEvent))
#1 /home/pierre/workspace/test/vendor/phpro/grumphp/src/Runner/TaskRunner.php(59): GrumPHP\Event\Dispatcher\Bridge\SymfonyEventDispatcher->dispatch(Object(GrumPHP\Event\RunnerEvent), 'grumphp.runner....')
#2 /home/pierre/workspace/test/vendor/phpro/grumphp/src/Console/Helper/TaskRunnerHelper.php(69): GrumPHP\Runner\TaskRunner->run(Object in /home/pierre/workspace/test/vendor/symfony/event-dispatcher/EventDispatcher.php on line 37
```

It seems to be because `symfony/contracts` is installed so `\GrumPHP\Event\Event` automatically extends it, but EventDispatcher requires an event that extends `Symfony\Component\EventDispatcher\Event`.

**Comment by veewee** [comment]
Hello,

We dropped support for Symfony 3 since previous release 0.19 and suggest to move forward.

You can always install the dependencyless phar version of grumphp to make it work without changing your projects requirements:
https://github.com/phpro/grumphp-shim

(It works exactly the same as this repository does)
