### ISSUE TITLE
STDIN is ignored in PHP 7.4.7

### ISSUE THREAD

**Issue by melkamar** [phpro/grumphp#787]
| Q               | A
| --------------- | ---
| Version         | GrumPHP 0.19.1
| Bug?            | yes
| New feature?    | no
| Question?       | no
| Documentation?  | no
| Related tickets | #770

**My configuration**
```yaml
grumphp:
    ascii: ~
    tasks:
        phpcsfixer2:
            config: "app/phpcs/.php_cs"
            diff: true
            verbose: true
```

**Steps to reproduce:**
```sh
# Generate empty folder
mkdir tmp
cd tmp
git init
echo "vendor" > .gitignore
pbpaste > grumphp.yml
composer require --dev phpro/grumphp

# Make any change, doesn't matter

# Run GrumPHP:
git add -A && git commit -m"Test"
# or
./vendor/bin/grumphp run
```

**Result:**
```
In ParserBase.php line 87:

  No match for regexp /diff --git (a\/.*) (b\/.*)\n/ Upcoming: diff --git c/i
  nstallation.yml


git:pre-commit [--skip-success-output] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-c|--config CONFIG] [--] <command>
```

**Comment**

_This error only happens after upgrading to PHP 7.4.7 from 7.3.x._

After upgrading to PHP 7.4, grumphp ignores the STDIN stream. Regardless of what I pass in, it always ignores it and goes with the default "no stdin provided" route. The command I use to call the tool is (truncated):

```bash
$ DIFF=$(git -c diff.mnemonicprefix=false --no-pager diff -r -p -m -M --full-index --no-color --staged | cat)
$ (cd "./" && printf "%s\n" "${DIFF}" | 'exec' 'vendor/bin/grumphp' 'git:pre-commit' '--skip-success-output')
```

The importance of calling the script with a custom STDIN is in the `-c diff.mnemonicprefix=false` config used to generate the `git diff`. Without this config the diff is in a format that causes the `ParserBase` exception shown above. 

I have traced the issue to this line of code: [`ConsoleIO:86`](https://github.com/phpro/grumphp/blob/master/src/IO/ConsoleIO.php#L86). Here the `ftell()` function returns `false`, which means that an empty string is returned from the method. If I change the line to 

```
if (0 !== ftell($handle) && false !== ftell($handle)) {
```

then everything works as expected and the stdin passed to grumphp is recognised. But I don't know if that is a sufficient fix as this might potentially hide other issues.

**Comment by veewee** [comment]
Thanks @melkamar  for the very detailed report.
I've created a fix for the stdin issue in #788. Looks like that one slipt in a couple of years ago.

To fix the invalid diff issue, you could change your git config or try changing it in the gitlib package.
More info:

* https://github.com/gitonomy/gitlib/issues/114
* https://github.com/gitonomy/gitlib/blob/master/src/Gitonomy/Git/WorkingCopy.php#L64-L69
