### ISSUE TITLE
Update your package to use latest composer version 2.0 - Very important!

### ISSUE THREAD

**Issue by gravataLonga** [phpro/grumphp#792]
| Q               | A
| --------------- | ---
| Version         | `GrumPHP 0.17.2`
| Bug?            |  ?
| New feature?    | no
| Question?       | no
| Documentation?  | non
| Related tickets | 

You need update your plugin, to use composer v2! This is very important. 

**My configuration**
```yaml
# grumphp.yml
# Please add a copy of your grumphp.yml file.
```

**Steps to reproduce:**
Install Composer Latest Version 2.0.
Install grumphp  
Then you get the issue.

**Comment by veewee** [comment]
Can you verify it works on grumphp 0.18.1?
We added support from that version

**Comment by gravataLonga** [comment]
Ohhh, thanks. Let me check..

**Comment by gravataLonga** [comment]
@veewee Yes can confirm it's work, thanks!
