### ISSUE TITLE
Create a Website for this Repo

### ISSUE THREAD

**Issue by xdvrx1** [phpro/grumphp#800]
Hi there. 

Is there a website for this repo? 

Because if you don't have, well, this repo can simply be turned into a website right away. Others will discover this project in that website.

Steps:
1. Go to Settings and look for `GitHub Pages`, scroll down. That's almost at the bottom.

2. You will see there: `Branch:none`, so you should change that to `master` because you have a `README.md` file in the master repo. This will be your page. Click `Save` first.

3. Then click `Choose a theme`, you select a predefined theme of your site.

4. Visit your site now! The URL will be `https://phpro.github.io/grumphp`. 

If you were amazed by that, simply read the documentation about GitHub Pages.

**Comment by veewee** [comment]
Thanks for the info! It's quite nice, but the themes are aweful.
I generated the site, but I don't really see the added value since the documentation is completely accessible from the repo itself.

https://phpro.github.io/grumphp

**Comment by xdvrx1** [comment]
Yup, the sense is that, aside from this repo, you have another domain that can be discovered by others, that is `github.io` domain or your own domain if you have one. It adds visibility on the web. 

Take note, `github.com` and `github.io`, they are two separate domains. And the good thing about GitHub Pages is that changes made in `README.md` file is reflected in the generated web page, so you don't need to worry about the page being outdated.

Plus, Jekyll is the static site generator behind GitHub Pages that you can download and create your own theme.

<https://jekyllrb.com/>

And you have the option to create your own design using pure HTML, JavaScript and CSS. Just make sure you replace `README.md` with `index.html`

**Comment by veewee** [comment]
Thanks for the feedback.
Gonna keep it like this for now.
