### ISSUE TITLE
Phpcs - how to allow no whitespace around concat operator 

### ISSUE THREAD

**Issue by kapdom** [phpro/grumphp#884]
How to ignore error when no space after concat operator.
All my config that I add to exclude not working, so how to write it correctly.

> 
>  22 | ERROR | [x] Expected at least 1 space before "."; 0 found
>  22 | ERROR | [x] Expected at least 1 space after "."; 0 found
> -------------------------------------------------------------------

This is my config:
```
grumphp:
  fixer:
    enabled: true
    fix_by_default: true
  git_hook_variables:
    DOCKER_CONTAINER: php
    DOCKER_HOME_DIRECTORY: /var/www/html
    EXEC_GRUMPHP_COMMAND: docker exec -i $(docker-compose ps -q php) php
    ENV: {}
  ascii:
    failed: vendor/phpro/grumphp/resources/ascii/nopecat.txt
    succeeded: vendor/phpro/grumphp/resources/ascii/grumphp-happy.txt
  tasks:
    #        securitychecker: ~
    phpcs:
      standard: ["PSR12", "PSR2", "PSR1"]
      exclude: ['Squiz.WhiteSpace.OperatorSpacing']
      warning_severity: 5
      whitelist_patterns:
        - /^src\/(.*)/
```

**Comment by veewee** [comment]
The exclude option feeds the `--exclude` property from phpcs.
If you have questions regarding phpcs config, I suggest you ask your questions in their repo instead.
