### ISSUE TITLE
Support GitHub Desktop

### ISSUE THREAD

**Issue by evs-xsarus** [phpro/grumphp#885]
Is it possible to support the hooks in GitHub Desktop?

https://desktop.github.com/

**Comment by veewee** [comment]
This package runs regular git hooks.
As I don't use github desktop, I can't tell what needs to happen from our side.
I assume that github desktop must trigger the hooks like any git client and display the error message on failure.

Feel free to create another issue or PR, If there is anything specific that we need to do from our side.
