### ISSUE TITLE
Cannot install v1.3.3

### ISSUE THREAD

**Issue by jensbhurtah** [phpro/grumphp#908]
Hello,
Since a few days, installation of v1.3.3 fails. it was working previously.
Installation of v1.3.2 works.
 
  - Installing phpro/grumphp (v1.3.3): Extracting archive
Plugin initialization failed (Plugin phpro/grumphp could not be initialized, class not found: GrumPHP\Composer\GrumPHPPlugin), uninstalling plugin

I cleared the cache of composer, the installation still fails.

Any idea ?
Thanks.

**Comment by veewee** [comment]
Hello @jensbhurtah,

Just tested it out locally on a fresh directory and seems to work. Maybe you can try again after running `composer self-update`?
Are there maybe any packages you got installed that are conflicting with grumphp?

**Comment by jensbhurtah** [comment]
Hello @veewee 

Thanks.
Manage to get it worked. 
Reinstalled composer.

it must have been a conflicts between package.
