### ISSUE TITLE
Grumphp future

### ISSUE THREAD

**Issue by x69420** [phpro/grumphp#973]
Hey guys, I tried to get grumphp + php-cs-fixer working but spent 2-3 hours basically for nothing, wasn't even able to read its source since it's so overengineered. I put it into subdirectory /tools and it just kept on not working whatever I tried (first had to set env variable to point to subdir vendors, then some other bs finder error, it shouldn't be that complicated).
Are there plans to properly develop into something more serious and useable? Cuz it really looked nice as a frontend for php-cs-fixer and I really didn't want to mess with git hooks. :<

**Comment by veewee** [comment]
Hello,

I'm sorry to hear you are having troubles setting up your tooling. 

This tool is being used in thousands of projects in combination with php-cs-fixer. Idd say it is pretty serious, usable and stable. I'm not sure if your complaining about GrumPHP or php-cs-fixer at this point.

In any case: Feel free to open up a more constructive QA issue in the discussion section.
